// Master pipeline configuration — XPS Contractor Acquisition Workflow
// Each phase contains stages, each stage has steps with actions

export const PIPELINE_PHASES = [
  {
    id: "phase_1",
    name: "PHASE 1 — DISCOVERY",
    description: "Build 3 databases through automated scraping",
    color: "#d4af37",
    stages: [
      {
        id: "scrape_contractors",
        name: "Scrape Contractors",
        icon: "Building2",
        color: "#d4af37",
        status: "active", // active | idle | complete
        type: "automated",
        frequency: "Every hour",
        description: "GCs, architects, project owners, superintendents — all key decision-makers at the start of any commercial project",
        database: "ContractorCompany",
        actions: ["Run Now", "View Database", "Configure"],
      },
      {
        id: "scrape_jobs",
        name: "Scrape Jobs",
        icon: "Briefcase",
        color: "#22c55e",
        status: "active",
        type: "automated",
        frequency: "Every hour",
        description: "Government (SAM.gov, BidNet) and commercial projects (Dodge, ConstructConnect, PlanHub) with flooring scope",
        database: "CommercialJob",
        actions: ["Run Now", "View Database", "Configure"],
      },
      {
        id: "scrape_competitors",
        name: "Scrape Competitors",
        icon: "Swords",
        color: "#ef4444",
        status: "active",
        type: "automated",
        frequency: "Every hour",
        description: "Epoxy, decorative concrete, and polished concrete companies — pricing, services, coverage areas",
        database: "FlooringCompetitor",
        actions: ["Run Now", "View Database", "Configure"],
      },
    ],
  },
  {
    id: "phase_2",
    name: "PHASE 2 — OUTREACH",
    description: "Automated introductions & relationship building",
    color: "#06b6d4",
    stages: [
      {
        id: "intro_campaign",
        name: "Introduction Campaign",
        icon: "Send",
        color: "#06b6d4",
        status: "idle",
        type: "automated",
        description: "Professional intro email/SMS/WhatsApp to GCs — XPS credentials, 60+ locations, 15yr veteran, bid list request, 48hr bid guarantee",
        actions: ["Preview Templates", "Send Test", "Configure"],
      },
      {
        id: "email_monitor",
        name: "Email Monitor",
        icon: "Mail",
        color: "#8b5cf6",
        status: "idle",
        type: "automated",
        frequency: "Every minute",
        description: "AI scans inbox continuously, auto-responds using templates, routes bid requests to contractor folders",
        actions: ["View Inbox", "Configure AI", "Templates"],
      },
      {
        id: "follow_up",
        name: "Follow-Up Engine",
        icon: "Clock",
        color: "#f59e0b",
        status: "idle",
        type: "automated",
        description: "Day 3, 7, 14, 30 follow-ups — professionally persistent until they can only think about XPS",
        actions: ["View Queue", "Configure", "Templates"],
      },
    ],
  },
  {
    id: "phase_3",
    name: "PHASE 3 — BID PROCESSING",
    description: "AI takeoff → triple validation → proposal generation",
    color: "#22c55e",
    stages: [
      {
        id: "ai_takeoff",
        name: "AI Takeoff",
        icon: "Sparkles",
        color: "#22c55e",
        status: "idle",
        type: "automated",
        description: "Immediate AI scan of drawings, floor plans — extract rooms, zones, sqft, systems, special requirements",
        actions: ["Upload Plans", "View Scope Sheet"],
      },
      {
        id: "validator_1",
        name: "Validator 1 — Accuracy",
        icon: "Shield",
        color: "#f59e0b",
        status: "idle",
        type: "automated",
        description: "Double-checks all measurements, quantities, material specs against industry best standards from top epoxy/polished concrete sites",
        actions: ["View Standards", "Configure"],
      },
      {
        id: "validator_2",
        name: "Validator 2 — Completeness",
        icon: "CheckCircle",
        color: "#14b8a6",
        status: "idle",
        type: "automated",
        description: "Ensures all scopes included, nothing missed, measurements verified, cross-referenced with original plans",
        actions: ["View Checklist"],
      },
      {
        id: "proposal_gen",
        name: "Proposal Generator",
        icon: "FileText",
        color: "#6366f1",
        status: "idle",
        type: "automated",
        description: "Full templated bid package — exceeds contractor expectations. Includes differentiators that set XPS apart from all competitors",
        actions: ["Preview Template", "Configure"],
      },
    ],
  },
  {
    id: "phase_4",
    name: "PHASE 4 — BID VALIDATION",
    description: "Ruthless QA — simulated competitors & scoring benchmarks",
    color: "#f59e0b",
    stages: [
      {
        id: "bid_validator_1",
        name: "Bid Critic Agent",
        icon: "AlertTriangle",
        color: "#ef4444",
        status: "idle",
        type: "automated",
        description: "Acts AS the contractor — deliberately finds every flaw, cross-references pricing vs competitors, tears the bid apart",
        actions: ["View Criteria", "Configure"],
      },
      {
        id: "bid_validator_2",
        name: "Competitive Simulator",
        icon: "Users",
        color: "#f97316",
        status: "idle",
        type: "automated",
        description: "3 simulated competitor bids side-by-side. Scoring benchmarks that must be met. Visual comparison dashboard",
        actions: ["View Benchmarks", "Simulate"],
      },
      {
        id: "scoring_gate",
        name: "Score Gate",
        icon: "Target",
        color: "#d4af37",
        status: "idle",
        type: "automated",
        description: "Must pass minimum score threshold to proceed. Based on top 20 methods to win commercial/gov work",
        actions: ["View Scorecard"],
      },
    ],
  },
  {
    id: "phase_5",
    name: "PHASE 5 — HUMAN APPROVAL",
    description: "Final review, comparison, and approval",
    color: "#8b5cf6",
    stages: [
      {
        id: "approval_queue",
        name: "Approval Queue",
        icon: "Inbox",
        color: "#8b5cf6",
        status: "idle",
        type: "manual",
        description: "Priority-sorted queue — AI recommendations, pricing comparison, simulated bid comparison, checklist, e-sign",
        actions: ["Open Queue", "Configure Priority"],
      },
      {
        id: "final_send",
        name: "Send & Sign",
        icon: "Send",
        color: "#22c55e",
        status: "idle",
        type: "automated",
        description: "Email bid + SMS link + digital signature + $500 price-beat guarantee + early payment discount incentives",
        actions: ["Preview Package"],
      },
    ],
  },
  {
    id: "phase_6",
    name: "PHASE 6 — CLOSE & NEGOTIATE",
    description: "Win the deal or learn why we didn't",
    color: "#ec4899",
    stages: [
      {
        id: "close_follow_up",
        name: "Close Follow-Up",
        icon: "PhoneCall",
        color: "#ec4899",
        status: "idle",
        type: "automated",
        description: "Automated email, text, calls — free floor maintenance package offer, professionally semi-constant presence",
        actions: ["View Templates", "Configure"],
      },
      {
        id: "negotiation",
        name: "Negotiation",
        icon: "Scale",
        color: "#f97316",
        status: "idle",
        type: "manual",
        description: "If they say no — rebut, negotiate price, ask why they chose another company to improve",
        actions: ["View Scripts"],
      },
      {
        id: "contract_sign",
        name: "Contract & Invoice",
        icon: "FileSignature",
        color: "#22c55e",
        status: "idle",
        type: "manual",
        description: "Final contracts, deposit, digital DocuSign — frictionless, zero bottlenecks, early payment incentives",
        actions: ["Generate Contract"],
      },
    ],
  },
  {
    id: "phase_7",
    name: "PHASE 7 — OPERATIONS",
    description: "Project execution with full client portal",
    color: "#0ea5e9",
    stages: [
      {
        id: "job_portal",
        name: "Client Job Portal",
        icon: "Layout",
        color: "#0ea5e9",
        status: "idle",
        type: "manual",
        description: "Client, PM, super, admin, owner sign-in — daily photos, reports, clarifications, change orders, messaging, calendar",
        actions: ["Open Portal"],
      },
      {
        id: "stage_tracking",
        name: "Stage Tracking",
        icon: "ListChecks",
        color: "#14b8a6",
        status: "idle",
        type: "automated",
        description: "Crew leader uploads photos per stage, client digitally approves each stage, delay tracking with reasons",
        actions: ["View Stages"],
      },
      {
        id: "final_walkthrough",
        name: "Final Walkthrough",
        icon: "Camera",
        color: "#22c55e",
        status: "idle",
        type: "manual",
        description: "Client + crew leader walk-through, final photos, client signature for warranty, floor care guides, cleaning instructions",
        actions: ["Start Walkthrough"],
      },
    ],
  },
  {
    id: "phase_8",
    name: "PHASE 8 — RETENTION",
    description: "Reviews, loyalty, referrals & recurring revenue",
    color: "#10b981",
    stages: [
      {
        id: "thank_you",
        name: "Thank You + Reviews",
        icon: "Gift",
        color: "#10b981",
        status: "idle",
        type: "automated",
        description: "$50 gift card for Google review, $100 for Google + FB + IG. Ship maintenance package. Annual photo maintenance schedule",
        actions: ["Preview Email", "Configure Rewards"],
      },
      {
        id: "loyalty_program",
        name: "Client Loyalty",
        icon: "Heart",
        color: "#ec4899",
        status: "idle",
        type: "automated",
        description: "$100 job discount for entering loyalty. Every referral that signs = 1 free year of cleaning & maintenance supplies",
        actions: ["Configure Program"],
      },
      {
        id: "recurring_followup",
        name: "Recurring Follow-Up",
        icon: "CalendarCheck",
        color: "#d4af37",
        status: "idle",
        type: "automated",
        description: "Monthly check-ins, promotions, new systems, specials, prize drawings — warranty requires our products only",
        actions: ["View Schedule", "Configure"],
      },
    ],
  },
];

// Flatten all stages for counting
export const ALL_STAGES = PIPELINE_PHASES.flatMap(p => p.stages);
export const TOTAL_STAGES = ALL_STAGES.length;