import LeadPipelineView from "../pipeline/LeadPipelineView";
import CRMView from "../dashboard/CRMView";
import FindJobsView from "../scraper/FindJobsView";
import FindCompaniesView from "../scraper/FindCompaniesView";
import ContactView from "../phases/ContactView";
import CloseView from "../phases/CloseView";
import AnalyticsView from "../dashboard/AnalyticsView";
import KnowledgeView from "../knowledge/KnowledgeView";
import KnowledgeUploadView from "../knowledge/KnowledgeUploadView";
import AdminControlView from "../admin/AdminControlView";
import CompetitiveIntelCenter from "../owner/CompetitiveIntelCenter";
import CompetitorComparisonView from "../competitor/CompetitorComparisonView";
import AgentKnowledgeUpload from "../dashboard/AgentKnowledgeUpload";
import AgentSkillsLibrary from "../dashboard/AgentSkillsLibrary";
import ConnectorHub from "../settings/ConnectorHub";
import BidCommandCenter from "../bidcenter/BidCommandCenter";
import MediaHub from "../media/MediaHub";
import SettingsView from "../dashboard/SettingsView";
import ScraperSchedulerView from "../scheduler/ScraperSchedulerView";
import WorkflowCreatorView from "../workflow/WorkflowCreatorView";
import DataBankView from "../databank/DataBankView";
import SocialScrapeView from "../scraper/SocialScrapeView";
import TrendsScrapeView from "../scraper/TrendsScrapeView";
import AlgorithmTuningView from "../settings/AlgorithmTuningView";
import SeedsSourcesView from "../scraper/SeedsSourcesView";
import AgentFleetView from "../agents/AgentFleetView";
import AgentBuilder from "../agents/AgentBuilder";
import ToolCreatorView from "../dashboard/ToolCreatorView";
import SystemHealthView from "../dashboard/SystemHealthView";
import BlueprintTakeoffView from "../takeoff/BlueprintTakeoffView";
import DynamicPricingView from "../pricing/DynamicPricingView";
import ProposalGeneratorView from "../proposals/ProposalGeneratorView";
import FieldTechEmbed from "../fieldtech/FieldTechEmbed";
import JobSiteMap from "../jobmap/JobSiteMap";
import AutoProposalGenerator from "../proposals/AutoProposalGenerator";
import ClientPortalView from "../clientportal/ClientPortalView";
import AgentCommandCenterView from "../commandcenter/AgentCommandCenter";
import OutreachAutomationView from "../outreach/OutreachAutomationView";
import SentimentAnalystView from "../sentiment/SentimentAnalystView";
import ProjectStatusReportView from "../reports/ProjectStatusReportView";
import BidPipelineDashboard from "../bidpipeline/BidPipelineDashboard";
import LeadSniperSystem from "../leadsniper/LeadSniperSystem";
import MasterPipelineView from "../pipeline/MasterPipelineView";
import ApprovalQueueView from "../approvals/ApprovalQueueView";
import CompanyAssetsView from "../companies/CompanyAssetsView";
import MasterScraperView from "../scraper/MasterScraperView";
import MasterDatabaseView from "../database/MasterDatabaseView";
import GitHubExplorerView from "../github/GitHubExplorerView";
import AgentSkillsCreatorView from "../agents/AgentSkillsCreatorView";
import TemplatesLibraryView from "../templates/TemplatesLibraryView";
import PageManagerView from "../layouteditor/PageManagerView";
import AutoEnhanceView from "../enhance/AutoEnhanceView";
import SystemIndexView from "../systemindex/SystemIndexView";
import AdminCommandCenter from "../systemindex/AdminCommandCenter";
import ComplianceCheckerView from "../compliance/ComplianceCheckerView";
import IntelCoreView from "../intelcore/IntelCoreView";
import HyperEvolverView from "../evolve/HyperEvolverView";
import SupabaseControlCenter from "../supabase/SupabaseControlCenter";
import OpenClawView from "../openclaw/OpenClawView";
import EditorWorkspace from "../editor/EditorWorkspace";
import SystemGuardianDashboard from "../guardian/SystemGuardianDashboard";
import FinancialSandboxView from "../financial/FinancialSandboxView";
import CryptoSimulationView from "../crypto/CryptoSimulationView";
import OrchestratorDashboard from "../orchestrator/OrchestratorDashboard";
import HeyGenAvatarStudio from "../heygen/HeyGenAvatarStudio";
import FocusDashboard from "../focus/FocusDashboard";
import UsageEstimatorView from "../dashboard/UsageEstimatorView";
import AutoDashboardConfigurator from "../dashboard/AutoDashboardConfigurator";
import AutoWorkflowEngine from "../dashboard/AutoWorkflowEngine";
import CallCenterView from "../callcenter/CallCenterView";
import StrategyView from "../strategy/StrategyView";
import SimulationView from "../simulation/SimulationView";
import EmailTemplatesView from "../outreach/EmailTemplatesView";
import CommandHub from "../commandhub/CommandHub";
import WarRoom from "../warroom/WarRoom";
import SystemOptimizationAnalyzer from "../systemoptimization/SystemOptimizationAnalyzer";
import AutomationCenter from "../automation/AutomationCenter";

export default function AppContent({ activeView, onChatCommand, onNavigate }) {
  switch (activeView) {
    case "master_pipeline": return <MasterPipelineView />;
    case "gc_bid_pipeline": return <BidPipelineDashboard />;
    case "lead_sniper": return <LeadSniperSystem />;
    case "xpress_leads": return <LeadPipelineView forcedTab="XPress" />;
    case "job_leads": return <LeadPipelineView forcedTab="Jobs" />;
    case "crm": return <WarRoom />;
    case "data_bank": return <DataBankView />;
    case "find_jobs": return <FindJobsView />;
    case "find_companies": return <FindCompaniesView />;
    case "scrape_social": return <SocialScrapeView />;
    case "scrape_trends": return <TrendsScrapeView />;
    case "get_work": return <ContactView />;
    case "win_work": return <CloseView />;
    case "analytics": return <AnalyticsView />;
    case "ai_assistant": return <KnowledgeView />;
    case "research": return <KnowledgeView />;
    case "knowledge": return <KnowledgeView />;
    case "knowledge_upload": return <KnowledgeUploadView />;
    case "seeds_sources": return <SeedsSourcesView />;
    case "algorithm": return <AlgorithmTuningView />;
    case "admin": return <AdminControlView />;
    case "competition": return <CompetitiveIntelCenter />;
    case "competitor_comparison": return <CompetitorComparisonView />;
    case "agent_knowledge": return <AgentKnowledgeUpload />;
    case "agent_skills": return <AgentSkillsLibrary onRunSkill={(cmd) => { /* handled by parent */ }} />;
    case "bid_center": return <BidCommandCenter />;
    case "media_hub": return <MediaHub />;
    case "connectors": return <ConnectorHub />;
    case "settings": return <SettingsView />;
    case "scheduler": return <ScraperSchedulerView />;
    case "workflows": return <WorkflowCreatorView />;
    case "agent_builder": return <AgentBuilder onSave={() => onNavigate?.("agent_fleet")} onCancel={() => onNavigate?.("agent_fleet")} />;
    case "agent_fleet": return <AgentFleetView />;
    case "tool_creator": return <ToolCreatorView onSave={(tool) => { /* Tool saved — handled by dashboard */ }} onBack={() => onNavigate?.("settings")} />;
    case "system_health": return <SystemHealthView />;
    case "blueprint_takeoff": return <BlueprintTakeoffView onNavigateToProposal={() => onNavigate?.("auto_proposal")} />;
    case "dynamic_pricing": return <DynamicPricingView />;
    case "proposal_generator": return <ProposalGeneratorView />;
    case "field_tech": return <FieldTechEmbed />;
    case "job_site_map": return <JobSiteMap />;
    case "auto_proposal": return <AutoProposalGenerator />;
    case "client_portal": return <ClientPortalView />;
    case "agent_command": return <AgentCommandCenterView />;
    case "outreach_automation": return <OutreachAutomationView />;
    case "sentiment_analyst": return <SentimentAnalystView />;
    case "status_reports": return <ProjectStatusReportView />;
    case "approval_queue": return <ApprovalQueueView />;
    case "company_assets": return <CompanyAssetsView />;
    case "master_scraper": return <MasterScraperView />;
    case "master_database": return <MasterDatabaseView />;
    case "github_explorer": return <GitHubExplorerView />;
    case "skills_creator": return <AgentSkillsCreatorView />;
    case "templates_library": return <TemplatesLibraryView />;
    case "page_builder": return <PageManagerView />;
    case "auto_enhance": return <AutoEnhanceView />;
    case "system_index": return <SystemIndexView />;
    case "system_instructions": return <AdminCommandCenter />;
    case "compliance_checker": return <ComplianceCheckerView />;
    case "xps_intel_core": return <IntelCoreView />;
    case "hyper_evolver": return <HyperEvolverView />;
    case "supabase_control": return <SupabaseControlCenter />;
    case "open_claw": return <OpenClawView />;
    case "editor_workspace": return <EditorWorkspace />;
    case "system_guardian": return <SystemGuardianDashboard />;
    case "financial_sandbox": return <FinancialSandboxView />;
    case "crypto_simulation": return <CryptoSimulationView />;
    case "orchestrator": return <WarRoom />;
    case "heygen_studio": return <HeyGenAvatarStudio />;
    case "focus_dashboard": return <FocusDashboard onOpenTool={onNavigate} />;
    case "usage_estimator": return <UsageEstimatorView />;
    case "auto_dashboard": return <div className="max-w-3xl mx-auto p-6"><AutoDashboardConfigurator onApply={() => onNavigate?.("dashboard")} /></div>;
    case "auto_workflow_engine": return <div className="max-w-3xl mx-auto p-6"><AutoWorkflowEngine onOpenTool={onNavigate} /></div>;
    case "call_center": return <WarRoom />;
    case "strategy_30day": return <StrategyView />;
    case "workflow_simulator": return <SimulationView />;
    case "email_templates": return <EmailTemplatesView />;
    case "system_optimization": return <div className="max-w-7xl mx-auto p-6"><SystemOptimizationAnalyzer /></div>;
    case "automation_center": return <div className="max-w-5xl mx-auto p-6"><AutomationCenter /></div>;
    case "master_ops": {
      window.location.href = "/master";
      return null;
    }
    case "ui_builder": return null; // Opens as standalone page at /ui-builder
    case "agent_zero": return null; // Opens as standalone page at /agent-zero
    default: return <div className="text-center py-20 text-muted-foreground">View not found</div>;
  }
}