import { Palette, Type, Bot, Zap, Link2, Layout, FileText, Phone, Mail, Globe, Briefcase, Lightbulb, MonitorSmartphone, Users, DollarSign, Layers, Sparkles } from "lucide-react";

export const TEMPLATE_CATEGORIES = [
  {
    id: "colors",
    title: "COLORS & THEMES",
    icon: Palette,
    desc: "Color palettes, gradients, and animated shade designs",
    templates: [
      { name: "Midnight Gold", preview: "🌑", desc: "Deep black with gold accents" },
      { name: "Arctic Silver", preview: "🌊", desc: "Cool silver-blue professional" },
      { name: "Carbon Fiber", preview: "⬛", desc: "Dark industrial carbon look" },
      { name: "Ocean Depth", preview: "🌊", desc: "Deep navy with teal highlights" },
      { name: "Sunset Ember", preview: "🔥", desc: "Warm orange-red gradient" },
      { name: "Forest Canopy", preview: "🌲", desc: "Rich green natural tones" },
      { name: "Royal Purple", preview: "👑", desc: "Deep purple with gold trim" },
      { name: "Copper Rust", preview: "🔶", desc: "Industrial copper-bronze" },
      { name: "Ice Crystal", preview: "❄️", desc: "Light blue crystalline" },
      { name: "Neon Pulse", preview: "💜", desc: "Vibrant neon accents on dark" },
      { name: "Sand Dune", preview: "🏜️", desc: "Warm desert sand tones" },
      { name: "Slate Storm", preview: "🌪️", desc: "Dark gray storm palette" },
      { name: "Cherry Blossom", preview: "🌸", desc: "Soft pink Japanese minimal" },
      { name: "Emerald City", preview: "💎", desc: "Rich emerald green luxury" },
      { name: "Titanium White", preview: "⬜", desc: "Clean white modern" },
      { name: "Volcanic Ash", preview: "🌋", desc: "Charcoal with red sparks" },
      { name: "Golden Hour", preview: "🌅", desc: "Warm golden sunset tones" },
      { name: "Deep Space", preview: "🚀", desc: "Ultra-dark with star accents" },
      { name: "Mahogany Wood", preview: "🪵", desc: "Rich wood-grain brown" },
      { name: "Electric Blue", preview: "⚡", desc: "Bright blue electric vibes" },
    ],
  },
  {
    id: "fonts",
    title: "FONTS & TYPOGRAPHY",
    icon: Type,
    desc: "Font combinations for headings and body text",
    templates: [
      { name: "Montserrat + Inter", desc: "Bold modern professional" },
      { name: "Playfair + Lato", desc: "Elegant serif combo" },
      { name: "Roboto Condensed", desc: "Tight industrial headers" },
      { name: "Oswald + Open Sans", desc: "Strong contrast pairing" },
      { name: "Raleway + Nunito", desc: "Light and airy" },
      { name: "Bebas Neue + Roboto", desc: "Impact sports style" },
      { name: "Poppins + Source Sans", desc: "Friendly rounded modern" },
      { name: "DM Sans + DM Serif", desc: "Elegant sans-serif combo" },
      { name: "Space Grotesk", desc: "Geometric tech style" },
      { name: "Archivo Black + Inter", desc: "Heavy impact headers" },
      { name: "Barlow Condensed", desc: "Narrow industrial" },
      { name: "Manrope + Outfit", desc: "Clean geometric duo" },
      { name: "Sora + IBM Plex", desc: "Tech-forward modern" },
      { name: "Lexend + Work Sans", desc: "Readable accessibility-first" },
      { name: "Clash Display", desc: "Bold contemporary display" },
      { name: "Plus Jakarta Sans", desc: "Polished startup aesthetic" },
      { name: "Cabinet Grotesk", desc: "Strong geometric headlines" },
      { name: "General Sans", desc: "Versatile neutral base" },
      { name: "Satoshi + Switzer", desc: "Balanced modern pair" },
      { name: "Red Hat Display", desc: "Friendly brand-forward" },
      { name: "Geist + Geist Mono", desc: "Developer-focused clean" },
      { name: "Albert Sans", desc: "Geometric humanist" },
      { name: "Figtree + Atkinson", desc: "Accessible modern" },
      { name: "Instrument Sans", desc: "Precise Swiss style" },
      { name: "Bricolage Grotesque", desc: "Expressive eclectic" },
      { name: "Onest + Wix Madefor", desc: "Fresh professional" },
      { name: "Noto Sans", desc: "Universal multilingual" },
      { name: "Rubik + Karla", desc: "Rounded approachable" },
      { name: "Urbanist + Mulish", desc: "Sleek startup pair" },
      { name: "Quicksand + Nunito", desc: "Soft rounded friendly" },
    ],
  },
  {
    id: "agents",
    title: "AI AGENTS",
    icon: Bot,
    desc: "Pre-built AI agents for every business function",
    templates: [
      { name: "Lead Qualifier", desc: "Auto-validates and scores new leads" },
      { name: "Email Writer", desc: "Drafts personalized outreach emails" },
      { name: "Proposal Generator", desc: "Creates professional proposals from specs" },
      { name: "Call Script Agent", desc: "Prepares tailored phone scripts" },
      { name: "Follow-Up Engine", desc: "Manages multi-touch sequences" },
      { name: "Invoice Creator", desc: "Generates and sends invoices" },
      { name: "Web Researcher", desc: "Deep research on companies and leads" },
      { name: "SEO Analyzer", desc: "Audits websites for SEO opportunities" },
      { name: "Social Media Manager", desc: "Creates and schedules social posts" },
      { name: "Competitor Tracker", desc: "Monitors competitor activity" },
      { name: "Review Collector", desc: "Automates review request sequences" },
      { name: "Territory Analyst", desc: "Maps market opportunities by area" },
      { name: "Content Writer", desc: "Blog posts, articles, case studies" },
      { name: "SMS Campaign Agent", desc: "Targeted text message campaigns" },
      { name: "Meeting Scheduler", desc: "AI-powered calendar management" },
      { name: "Budget Forecaster", desc: "Revenue and expense predictions" },
      { name: "Customer Success", desc: "Post-sale satisfaction monitoring" },
      { name: "Data Cleaner", desc: "Dedupes and enriches contact data" },
      { name: "Report Generator", desc: "Weekly/monthly business summaries" },
      { name: "Contract Reviewer", desc: "AI analysis of contract terms" },
      { name: "Price Optimizer", desc: "Dynamic pricing recommendations" },
      { name: "Churn Predictor", desc: "Identifies at-risk accounts" },
      { name: "Onboarding Guide", desc: "Walks new users through setup" },
      { name: "Helpdesk Agent", desc: "Handles customer support tickets" },
      { name: "Inventory Manager", desc: "Tracks materials and supplies" },
      { name: "Quality Inspector", desc: "Post-job quality checklists" },
      { name: "Training Coach", desc: "Skill development recommendations" },
      { name: "Legal Compliance", desc: "License and permit tracking" },
      { name: "Fleet Manager", desc: "Vehicle and equipment scheduling" },
      { name: "Payroll Assistant", desc: "Timesheet and payment processing" },
    ],
  },
  {
    id: "agent_skills",
    title: "AGENT SKILLS",
    icon: Sparkles,
    desc: "Individual capabilities to add to any agent",
    templates: [
      { name: "Web Search", desc: "Search the internet for information" },
      { name: "Email Sending", desc: "Send emails via integrated SMTP" },
      { name: "SMS Sending", desc: "Send text messages via Twilio" },
      { name: "File Upload", desc: "Upload and process documents" },
      { name: "Image Generation", desc: "Create AI images from prompts" },
      { name: "Data Extraction", desc: "Pull structured data from files" },
      { name: "PDF Generation", desc: "Create formatted PDF documents" },
      { name: "Calendar Integration", desc: "Schedule and manage events" },
      { name: "CRM Read/Write", desc: "Access and update lead data" },
      { name: "Invoice Generation", desc: "Create professional invoices" },
      { name: "Proposal Building", desc: "Generate proposals from templates" },
      { name: "Lead Scoring", desc: "AI-powered lead qualification" },
      { name: "Sentiment Analysis", desc: "Analyze text for tone and mood" },
      { name: "Translation", desc: "Multi-language text translation" },
      { name: "Voice Synthesis", desc: "Text-to-speech generation" },
      { name: "OCR Processing", desc: "Extract text from images" },
      { name: "Chart Generation", desc: "Create data visualizations" },
      { name: "Social Posting", desc: "Post to social media platforms" },
      { name: "Form Filling", desc: "Auto-complete web forms" },
      { name: "Code Generation", desc: "Write and execute code" },
      { name: "Database Query", desc: "Query and filter entity data" },
      { name: "Webhook Trigger", desc: "Send data to external systems" },
      { name: "Spreadsheet Ops", desc: "Read/write Google Sheets" },
      { name: "Link Shortening", desc: "Create trackable short URLs" },
      { name: "QR Code Generation", desc: "Generate QR codes for links" },
      { name: "HTML to PDF", desc: "Convert web pages to documents" },
      { name: "JSON Parsing", desc: "Extract and transform JSON data" },
      { name: "Regex Matching", desc: "Pattern match in text content" },
      { name: "Rate Limiting", desc: "Throttle API call frequency" },
      { name: "Error Handling", desc: "Graceful failure recovery" },
      { name: "Batch Processing", desc: "Process items in bulk" },
      { name: "Scheduled Execution", desc: "Run tasks on a timer" },
      { name: "Conditional Logic", desc: "If/else workflow branching" },
      { name: "Loop Iteration", desc: "Repeat actions over lists" },
      { name: "Approval Workflow", desc: "Human-in-the-loop checkpoints" },
      { name: "Deduplication", desc: "Remove duplicate records" },
      { name: "Data Validation", desc: "Verify data integrity" },
      { name: "Cache Management", desc: "Store and retrieve cached data" },
      { name: "Notification Push", desc: "Send push notifications" },
      { name: "Audit Logging", desc: "Track all agent actions" },
      { name: "A/B Testing", desc: "Split test message variants" },
      { name: "Geo Lookup", desc: "Location and address services" },
      { name: "Company Enrichment", desc: "Enrich company data from web" },
      { name: "Contact Enrichment", desc: "Find missing contact details" },
      { name: "Keyword Extraction", desc: "Pull keywords from content" },
      { name: "Summarization", desc: "Condense long text to bullets" },
      { name: "Categorization", desc: "Auto-tag and categorize items" },
      { name: "Priority Ranking", desc: "Score and rank items by criteria" },
      { name: "Template Merging", desc: "Fill templates with dynamic data" },
      { name: "Version Control", desc: "Track document revisions" },
    ],
  },
  {
    id: "connections",
    title: "CONNECTIONS & INTEGRATIONS",
    icon: Link2,
    desc: "Pre-configured service connections",
    templates: [
      { name: "Google Calendar", desc: "Schedule management" },
      { name: "Google Drive", desc: "Document storage" },
      { name: "Google Sheets", desc: "Spreadsheet data" },
      { name: "Gmail", desc: "Email integration" },
      { name: "Google Docs", desc: "Document editing" },
      { name: "Google Tasks", desc: "Task management" },
      { name: "HubSpot CRM", desc: "CRM sync" },
      { name: "Slack", desc: "Team messaging" },
      { name: "Twilio SMS", desc: "Text messaging" },
      { name: "Stripe", desc: "Payment processing" },
      { name: "QuickBooks", desc: "Accounting" },
      { name: "Zapier", desc: "Workflow automation" },
      { name: "GitHub", desc: "Code repository" },
      { name: "Notion", desc: "Knowledge base" },
      { name: "Airtable", desc: "Database tables" },
      { name: "Salesforce", desc: "Enterprise CRM" },
      { name: "LinkedIn", desc: "Professional network" },
      { name: "Facebook Ads", desc: "Ad management" },
      { name: "Google Ads", desc: "PPC campaigns" },
      { name: "Supabase", desc: "Backend database" },
    ],
  },
  {
    id: "workflows",
    title: "WORKFLOWS",
    icon: Zap,
    desc: "Pre-built automation workflows",
    templates: [
      { name: "Lead → Qualify → Contact", desc: "Full inbound pipeline" },
      { name: "Scrape → Enrich → Score", desc: "Auto lead generation" },
      { name: "Email → Follow-Up → Close", desc: "Outreach sequence" },
      { name: "Proposal → Invoice → Collect", desc: "Revenue pipeline" },
      { name: "Job Complete → Review → Referral", desc: "Post-job automation" },
      { name: "Morning Briefing", desc: "Daily summary at 7am" },
      { name: "Weekly Report Generator", desc: "Auto weekly analytics" },
      { name: "New Lead Alert", desc: "Instant notifications" },
      { name: "Stale Lead Reactivation", desc: "Re-engage cold leads" },
      { name: "Birthday/Anniversary", desc: "Client relationship nurture" },
      { name: "Competitor Monitor", desc: "Track competitor changes" },
      { name: "Price List Updater", desc: "Sync pricing across docs" },
      { name: "Invoice Reminder Chain", desc: "Auto payment follow-ups" },
      { name: "Onboarding Sequence", desc: "New client welcome flow" },
      { name: "Quality Check Audit", desc: "Post-job inspection flow" },
      { name: "Material Reorder Alert", desc: "Low inventory triggers" },
      { name: "Contract Renewal", desc: "Upcoming renewal reminders" },
      { name: "Social Post Scheduler", desc: "Auto social media queue" },
      { name: "SEO Rank Tracker", desc: "Weekly ranking reports" },
      { name: "Team Performance", desc: "Crew productivity metrics" },
    ],
  },
  {
    id: "industries",
    title: "INDUSTRY TEMPLATES",
    icon: Briefcase,
    desc: "Complete setup for specific industries",
    templates: [
      { name: "Epoxy Flooring", desc: "Commercial & residential coatings" },
      { name: "Polished Concrete", desc: "Diamond grinding & polishing" },
      { name: "General Contracting", desc: "Multi-trade construction" },
      { name: "HVAC Services", desc: "Heating, ventilation, AC" },
      { name: "Plumbing", desc: "Residential & commercial" },
      { name: "Electrical", desc: "Wiring & panel services" },
      { name: "Roofing", desc: "Roof install & repair" },
      { name: "Landscaping", desc: "Outdoor & hardscape" },
      { name: "Painting", desc: "Interior & exterior" },
      { name: "Property Management", desc: "Multi-unit management" },
      { name: "Real Estate", desc: "Agent & broker tools" },
      { name: "Auto Detailing", desc: "Vehicle care services" },
      { name: "Pressure Washing", desc: "Surface cleaning" },
      { name: "Solar Installation", desc: "Solar panel services" },
      { name: "Pool Services", desc: "Pool maintenance & install" },
      { name: "Pest Control", desc: "Pest management" },
      { name: "Moving Services", desc: "Relocation & logistics" },
      { name: "Cleaning Services", desc: "Commercial & residential" },
      { name: "Fencing", desc: "Fence install & repair" },
      { name: "Window Tinting", desc: "Auto & commercial tint" },
    ],
  },
  {
    id: "proposals",
    title: "PROPOSALS & BIDS",
    icon: FileText,
    desc: "Proposal and bidding templates",
    templates: [
      { name: "Standard Proposal", desc: "Clean professional layout" },
      { name: "Premium Proposal", desc: "Photo-heavy premium feel" },
      { name: "Quick Quote", desc: "One-page fast estimate" },
      { name: "Government RFP", desc: "Formal bid response" },
      { name: "Multi-Phase Project", desc: "Phased work breakdown" },
      { name: "Maintenance Contract", desc: "Recurring service agreement" },
      { name: "Emergency Repair", desc: "Urgent repair quote" },
      { name: "Design-Build", desc: "Conceptual + execution" },
      { name: "Subcontractor Bid", desc: "Sub bid package" },
      { name: "Change Order", desc: "Scope change documentation" },
      { name: "Material Only Quote", desc: "Supply-only pricing" },
      { name: "Labor + Material", desc: "Complete T&M breakdown" },
      { name: "Warranty Extension", desc: "Extended warranty offer" },
      { name: "Site Assessment", desc: "Pre-project evaluation" },
      { name: "Training Package", desc: "Training services proposal" },
      { name: "Annual Contract", desc: "Yearly service agreement" },
      { name: "Competitive Bid", desc: "Side-by-side comparison" },
      { name: "Value Engineering", desc: "Cost-saving alternatives" },
      { name: "Insurance Claim", desc: "Restoration estimate" },
      { name: "Product Demo", desc: "Sample/demo proposal" },
    ],
  },
  {
    id: "invoicing",
    title: "INVOICING & BILLING",
    icon: DollarSign,
    desc: "Invoice and billing templates",
    templates: [
      { name: "Standard Invoice", desc: "Clean line-item invoice" },
      { name: "Progress Billing", desc: "Milestone-based payments" },
      { name: "Retainer Invoice", desc: "Monthly retainer billing" },
      { name: "Time & Material", desc: "Hourly + materials breakdown" },
      { name: "Deposit Request", desc: "Upfront deposit invoice" },
      { name: "Final Payment", desc: "Completion payment notice" },
      { name: "Credit Memo", desc: "Adjustment/credit note" },
      { name: "Recurring Invoice", desc: "Auto-generated monthly" },
      { name: "Past Due Notice", desc: "Overdue payment reminder" },
      { name: "Payment Plan", desc: "Installment schedule" },
      { name: "Commercial Invoice", desc: "Business-to-business" },
      { name: "Per Diem Invoice", desc: "Daily rate billing" },
      { name: "Equipment Rental", desc: "Rental fee breakdown" },
      { name: "Consulting Fee", desc: "Advisory services" },
      { name: "Warranty Claim", desc: "Warranty work billing" },
      { name: "Multi-Job Invoice", desc: "Consolidated billing" },
      { name: "International", desc: "Multi-currency support" },
      { name: "Tax-Exempt", desc: "Government/non-profit" },
      { name: "Deposit + Balance", desc: "Split payment invoice" },
      { name: "Estimates to Invoice", desc: "Convert quote to bill" },
    ],
  },
  {
    id: "ai_calls",
    title: "AI PHONE CALL SCRIPTS",
    icon: Phone,
    desc: "Pre-built call scripts for every scenario",
    templates: [
      { name: "Cold Intro Call", desc: "First-time contact opener" },
      { name: "Warm Lead Follow-Up", desc: "Website inquiry callback" },
      { name: "Referral Call", desc: "Referred lead approach" },
      { name: "Quote Follow-Up", desc: "Check on sent proposal" },
      { name: "Job Completion Check", desc: "Post-job satisfaction call" },
      { name: "Payment Reminder", desc: "Friendly invoice follow-up" },
      { name: "Upsell Opportunity", desc: "Additional services pitch" },
      { name: "Reactivation Call", desc: "Re-engage past customer" },
      { name: "Appointment Setter", desc: "Schedule site visit" },
      { name: "Objection Handler", desc: "Price concern response" },
      { name: "Decision Maker Reach", desc: "Get to the right person" },
      { name: "Competitive Win-Back", desc: "Lost to competitor recovery" },
      { name: "Annual Review", desc: "Yearly maintenance check" },
      { name: "Emergency Response", desc: "Urgent repair outreach" },
      { name: "Partnership Pitch", desc: "B2B partnership approach" },
    ],
  },
  {
    id: "email_templates",
    title: "AI EMAIL TEMPLATES",
    icon: Mail,
    desc: "Email templates for every workflow stage",
    templates: [
      { name: "Cold Outreach", desc: "First-touch prospecting email" },
      { name: "Follow-Up #1", desc: "3-day follow-up" },
      { name: "Follow-Up #2", desc: "7-day follow-up" },
      { name: "Follow-Up #3", desc: "Final attempt" },
      { name: "Proposal Send", desc: "Attached proposal delivery" },
      { name: "Thank You Post-Job", desc: "Completion appreciation" },
      { name: "Review Request", desc: "Ask for 5-star review" },
      { name: "Referral Ask", desc: "Request for referrals" },
      { name: "Invoice Delivery", desc: "Invoice attached email" },
      { name: "Payment Reminder", desc: "Overdue notice" },
      { name: "Seasonal Promo", desc: "Limited-time offer" },
      { name: "Newsletter", desc: "Monthly update blast" },
      { name: "Case Study Share", desc: "Social proof email" },
      { name: "Welcome Onboard", desc: "New client welcome" },
      { name: "Re-engagement", desc: "Cold lead reactivation" },
    ],
  },
  {
    id: "pipelines",
    title: "PIPELINE TEMPLATES",
    icon: Layers,
    desc: "Pre-built pipeline stage configurations",
    templates: [
      { name: "Standard Sales", desc: "Incoming → Qualified → Won" },
      { name: "High-Volume Leads", desc: "Bulk processing pipeline" },
      { name: "Enterprise Sales", desc: "Long-cycle B2B pipeline" },
      { name: "Project Pipeline", desc: "Bid → Award → Execute" },
      { name: "Service Pipeline", desc: "Request → Schedule → Complete" },
      { name: "Maintenance Pipeline", desc: "Inspect → Quote → Maintain" },
      { name: "Recruitment Pipeline", desc: "Source → Interview → Hire" },
      { name: "Real Estate Pipeline", desc: "Listing → Showing → Close" },
      { name: "Insurance Pipeline", desc: "Claim → Assess → Settle" },
      { name: "SaaS Sales Pipeline", desc: "Trial → Demo → Subscribe" },
      { name: "E-Commerce Pipeline", desc: "Cart → Checkout → Deliver" },
      { name: "Consulting Pipeline", desc: "Discover → Scope → Engage" },
      { name: "Partnership Pipeline", desc: "Outreach → Negotiate → Sign" },
      { name: "Event Pipeline", desc: "Plan → Market → Execute" },
      { name: "Product Launch", desc: "Build → Beta → Release" },
      { name: "Customer Success", desc: "Onboard → Adopt → Expand" },
      { name: "Support Ticket", desc: "Open → Triage → Resolve" },
      { name: "Content Pipeline", desc: "Draft → Edit → Publish" },
      { name: "Vendor Pipeline", desc: "Evaluate → Contract → Manage" },
      { name: "Training Pipeline", desc: "Enroll → Complete → Certify" },
    ],
  },
  {
    id: "layouts",
    title: "CENTER UI LAYOUTS",
    icon: Layout,
    desc: "Full center panel layout templates",
    templates: [
      { name: "Command Center", desc: "Dashboard with card grid" },
      { name: "Pipeline Focus", desc: "Full-width pipeline view" },
      { name: "Split Panel", desc: "50/50 list + detail" },
      { name: "Kanban Board", desc: "Drag-and-drop columns" },
      { name: "Calendar View", desc: "Monthly/weekly schedule" },
      { name: "Analytics Dashboard", desc: "Charts and KPIs" },
      { name: "CRM Board", desc: "Deal tracking board" },
      { name: "Feed Layout", desc: "Activity feed + sidebar" },
      { name: "Cards Grid", desc: "Responsive card mosaic" },
      { name: "Table View", desc: "Data table with filters" },
      { name: "Timeline View", desc: "Chronological activity" },
      { name: "Map View", desc: "Geographic lead display" },
      { name: "Gallery View", desc: "Visual portfolio grid" },
      { name: "Inbox Layout", desc: "Email-style list + preview" },
      { name: "Wizard Layout", desc: "Step-by-step process" },
      { name: "Report Layout", desc: "Printable report format" },
      { name: "Chat Focus", desc: "Full-width AI chat" },
      { name: "Comparison", desc: "Side-by-side comparison" },
      { name: "Minimal", desc: "Clean single-focus view" },
      { name: "Dense Data", desc: "Maximum info density" },
    ],
  },
  {
    id: "website_themes",
    title: "WEBSITE THEMES",
    icon: Globe,
    desc: "Complete website theme packages",
    templates: [
      { name: "Contractor Pro", desc: "Bold industrial with gold" },
      { name: "Clean Corporate", desc: "Professional business site" },
      { name: "Minimal Studio", desc: "White space minimalist" },
      { name: "Dark Executive", desc: "Premium dark executive" },
      { name: "Neon Tech", desc: "Vibrant tech startup" },
      { name: "Warm Artisan", desc: "Handcrafted organic feel" },
      { name: "Bold Impact", desc: "Big type, bold colors" },
      { name: "Luxury Brand", desc: "High-end luxury aesthetic" },
      { name: "Government", desc: "ADA compliant official" },
      { name: "Healthcare", desc: "Clean medical professional" },
      { name: "Education", desc: "Friendly learning platform" },
      { name: "E-Commerce", desc: "Product-focused retail" },
      { name: "Creative Agency", desc: "Portfolio showcase" },
      { name: "Real Estate", desc: "Property listing focused" },
      { name: "Restaurant", desc: "Food & hospitality" },
      { name: "Automotive", desc: "Vehicle services theme" },
      { name: "Fitness", desc: "Gym & wellness theme" },
      { name: "Legal", desc: "Law firm professional" },
      { name: "Non-Profit", desc: "Charity & cause driven" },
      { name: "SaaS Product", desc: "Software product site" },
      { name: "Photography", desc: "Visual gallery focus" },
      { name: "Construction", desc: "Building & trade services" },
      { name: "Blog Magazine", desc: "Content-first editorial" },
      { name: "Wedding", desc: "Event & celebration" },
      { name: "Music Artist", desc: "Band & musician site" },
    ],
  },
  {
    id: "landing_pages",
    title: "LANDING PAGES",
    icon: MonitorSmartphone,
    desc: "High-converting landing page templates",
    templates: [
      { name: "Hero + CTA", desc: "Simple hero with call to action" },
      { name: "Feature Showcase", desc: "3-column feature grid" },
      { name: "Testimonial Heavy", desc: "Social proof focused" },
      { name: "Video Hero", desc: "Background video landing" },
      { name: "Lead Magnet", desc: "Free download capture" },
      { name: "Product Launch", desc: "Coming soon countdown" },
      { name: "Pricing Page", desc: "3-tier pricing table" },
      { name: "Case Study", desc: "Results-driven layout" },
      { name: "Event Registration", desc: "Event signup page" },
      { name: "Waitlist", desc: "Early access signup" },
      { name: "Comparison", desc: "Us vs. competition" },
      { name: "Long-Form Sales", desc: "Scrolling sales letter" },
      { name: "App Download", desc: "Mobile app promotion" },
      { name: "Thank You", desc: "Post-conversion page" },
      { name: "404 Creative", desc: "Branded error page" },
      { name: "Webinar Signup", desc: "Live event registration" },
      { name: "Free Trial", desc: "SaaS trial signup" },
      { name: "Contact Us", desc: "Inquiry form page" },
      { name: "About Us", desc: "Company story page" },
      { name: "Portfolio", desc: "Work showcase page" },
    ],
  },
  {
    id: "tips_systems",
    title: "TIPS & TRICKS SYSTEMS",
    icon: Lightbulb,
    desc: "Industry-specific knowledge systems",
    templates: [
      { name: "Flooring Pro Tips", desc: "Surface prep, materials, techniques" },
      { name: "Sales Mastery", desc: "Closing techniques and scripts" },
      { name: "HVAC Handbook", desc: "System diagnostics and repair tips" },
      { name: "Plumbing Solutions", desc: "Common fixes and code compliance" },
      { name: "Electrical Safety", desc: "NEC code tips and best practices" },
      { name: "Roofing Guide", desc: "Material selection and install tips" },
      { name: "Painting Mastery", desc: "Prep, application, finish quality" },
      { name: "Concrete Finishing", desc: "Grinding, polishing, coating" },
      { name: "Business Finance", desc: "Cash flow, pricing, tax tips" },
      { name: "Marketing Playbook", desc: "Digital marketing for trades" },
      { name: "Customer Service", desc: "Client retention strategies" },
      { name: "Time Management", desc: "Productivity for contractors" },
      { name: "Safety & OSHA", desc: "Workplace safety compliance" },
      { name: "Equipment Care", desc: "Maintenance and longevity" },
      { name: "Hiring & HR", desc: "Recruitment and team building" },
      { name: "Insurance Guide", desc: "Coverage types and claims" },
      { name: "Licensing Guide", desc: "State requirements by trade" },
      { name: "Vehicle Fleet", desc: "Fleet management tips" },
      { name: "Seasonal Planning", desc: "Year-round business strategy" },
      { name: "Exit Strategy", desc: "Business valuation and sale" },
    ],
  },
  {
    id: "follow_up",
    title: "FOLLOW-UP SYSTEMS",
    icon: Users,
    desc: "Automated follow-up sequences",
    templates: [
      { name: "3-Touch Email", desc: "Day 1, 3, 7 email sequence" },
      { name: "5-Touch Multi-Channel", desc: "Email + SMS + call combo" },
      { name: "Post-Quote Follow-Up", desc: "After sending proposal" },
      { name: "Post-Job Nurture", desc: "Completed job relationship" },
      { name: "Annual Check-In", desc: "Yearly client maintenance" },
      { name: "Referral Request Chain", desc: "Ask + remind + thank" },
      { name: "Review Collection", desc: "Automated review requests" },
      { name: "Payment Reminder", desc: "Invoice follow-up sequence" },
      { name: "Stale Lead Revival", desc: "30/60/90 day reactivation" },
      { name: "Seasonal Campaign", desc: "Quarterly touch points" },
      { name: "Event Follow-Up", desc: "Post-meeting sequence" },
      { name: "Demo Follow-Up", desc: "After product demo" },
      { name: "Warranty Expiry", desc: "Renewal reminder chain" },
      { name: "Cross-Sell Sequence", desc: "Additional service offers" },
      { name: "Lost Deal Revival", desc: "Re-engage lost prospects" },
      { name: "VIP Client Care", desc: "High-value client nurture" },
      { name: "New Area Launch", desc: "Territory expansion outreach" },
      { name: "Price Change Notice", desc: "Rate increase notification" },
      { name: "Holiday Greeting", desc: "Seasonal relationship builder" },
      { name: "Milestone Celebration", desc: "Anniversary/achievement" },
    ],
  },
];