import {
  Globe, Database, FileSearch, CheckCircle, Star, FolderOpen,
  Brain, PhoneCall, Mail, Target, BarChart3, TrendingUp,
  Zap, Bot, MessageSquare, Shield, Search, Layers,
  Sparkles, GitBranch, ArrowDownToLine, Filter, Award,
  Users, Briefcase, Building2, Send, FileText, Clock,
  Upload, Share2, Sliders, BookOpen, Image, Video,
  Phone, Mic, MousePointer, RefreshCcw, AlertTriangle,
  Copy, Play, Pause, MoreHorizontal, Settings, Link2,
  DollarSign, Map, Swords, Truck, Hash, CalendarDays
} from "lucide-react";

// ── Master node registry — every tool, function, agent mapped ──
const NODE_REGISTRY = [
  {
    category: "Triggers",
    color: "#f59e0b",
    icon: Zap,
    desc: "Start your workflow",
    nodes: [
      { type: "trigger_manual", label: "Manual Trigger", icon: Play, desc: "Run manually", fn: null },
      { type: "trigger_schedule", label: "Schedule", icon: Clock, desc: "Run on a cron/interval", fn: null },
      { type: "trigger_new_lead", label: "New Lead Created", icon: Users, desc: "Fires when a lead enters the system", fn: null },
      { type: "trigger_lead_scored", label: "Lead Scored", icon: Star, desc: "Fires when a lead is scored", fn: null },
      { type: "trigger_bid_found", label: "Bid Opportunity Found", icon: Briefcase, desc: "Fires when a new commercial job is discovered", fn: null },
      { type: "trigger_email_opened", label: "Email Opened", icon: Mail, desc: "Fires when an outreach email is opened", fn: null },
      { type: "trigger_webhook", label: "Webhook", icon: Link2, desc: "External webhook trigger", fn: null },
    ],
  },
  {
    category: "Lead Generation",
    color: "#d4af37",
    icon: Users,
    desc: "Find and create leads",
    nodes: [
      { type: "lead_scraper", label: "AI Lead Scraper", icon: Search, desc: "Find leads by location, industry, keywords", fn: "leadScraper", params: ["location", "industry", "keywords", "count", "vertical"] },
      { type: "bulk_pipeline", label: "Bulk Lead Pipeline", icon: Layers, desc: "Full pipeline: scrape → score → enrich → research", fn: "bulkLeadPipeline", params: ["locations", "count_per_location", "industry"] },
      { type: "xpress_scraper", label: "XPress Scraper", icon: Target, desc: "AZ contractor leads", fn: "xpressLeadScraper", params: ["count"] },
      { type: "jobs_scraper", label: "Jobs Scraper", icon: Briefcase, desc: "End-buyer job leads", fn: "jobsLeadScraper", params: ["count"] },
      { type: "timed_scraper", label: "Timed Lead Scraper", icon: Clock, desc: "Multi-source timed scraper", fn: "timedLeadScraper", params: ["location", "industry", "keywords", "count"] },
      { type: "custom_scraper", label: "Custom Scraper", icon: Globe, desc: "Custom keyword/URL scraper", fn: "customScraper", params: ["keywords", "state", "city", "count", "urls"] },
      { type: "registry_scraper", label: "Registry Scraper", icon: Building2, desc: "State business registry scraper", fn: "registryScraper", params: ["states", "batch_size"] },
    ],
  },
  {
    category: "Job & Bid Discovery",
    color: "#22c55e",
    icon: Briefcase,
    desc: "Find commercial projects",
    nodes: [
      { type: "discover_jobs", label: "Discover Bid Jobs", icon: Briefcase, desc: "Gov & commercial bid opportunities", fn: "discoverBidJobs", params: ["states", "project_types", "sector"] },
      { type: "scrape_contractors", label: "Scrape Contractors", icon: Building2, desc: "Find GCs, subs, architects", fn: "scrapeContractors", params: ["states", "contractor_type", "limit"] },
      { type: "ai_takeoff", label: "AI Takeoff", icon: BarChart3, desc: "Zone-by-zone cost estimation", fn: "aiTakeoff", params: ["job_id"] },
      { type: "generate_bid", label: "Generate Bid Package", icon: FileText, desc: "Branded bid document", fn: "generateBidPackage", params: ["job_id"] },
      { type: "send_intro", label: "Send Intro Package", icon: Send, desc: "Intro package to contractors", fn: "sendIntroPackage", params: ["contractor_id"] },
    ],
  },
  {
    category: "Data Processing",
    color: "#6366f1",
    icon: Database,
    desc: "Clean, score, enrich data",
    nodes: [
      { type: "lead_scorer", label: "Lead Scorer", icon: Star, desc: "AI multi-factor scoring", fn: "leadScorer", params: ["lead_id", "batch_all", "min_score"] },
      { type: "contact_enricher", label: "Contact Enricher", icon: Users, desc: "Find decision-maker data", fn: "contactEnricher", params: ["lead_id", "company_name"] },
      { type: "validate_enrich", label: "Validate & Enrich", icon: CheckCircle, desc: "Verify business + enrich", fn: "validateAndEnrichLead", params: ["lead_id"] },
      { type: "dedup", label: "Deduplication", icon: Copy, desc: "Remove duplicate records", fn: null },
      { type: "filter_leads", label: "Filter / Condition", icon: Filter, desc: "Only pass matching records", fn: null, params: ["field", "operator", "value"] },
      { type: "data_transform", label: "Data Transform", icon: RefreshCcw, desc: "Map, rename, restructure fields", fn: null },
    ],
  },
  {
    category: "Research & Intelligence",
    color: "#8b5cf6",
    icon: Brain,
    desc: "Deep research and analysis",
    nodes: [
      { type: "web_research", label: "Web Research", icon: Search, desc: "Deep web research", fn: "webResearch", params: ["query", "url", "category", "deep_analysis"] },
      { type: "deep_research", label: "Deep Company Intel", icon: Brain, desc: "Multi-source company profile", fn: "deepResearch", params: ["lead_id", "company_name", "url"] },
      { type: "knowledge_search", label: "Knowledge Search", icon: BookOpen, desc: "Search internal knowledge base", fn: "knowledgeSearch", params: ["query", "category"] },
      { type: "knowledge_scraper", label: "Knowledge Scraper", icon: Upload, desc: "Scrape into knowledge base", fn: "knowledgeScraper", params: ["url", "urls", "category"] },
      { type: "territory_analyzer", label: "Territory Analyzer", icon: Map, desc: "Analyze market opportunity", fn: "territoryAnalyzer", params: ["city", "state", "radius_miles"] },
      { type: "competitor_scrape", label: "Competitor Scrape", icon: Swords, desc: "Competitor data extraction", fn: "competitorScrape", params: ["company_name", "url"] },
      { type: "manufacturer_profiler", label: "Manufacturer Profiler", icon: Building2, desc: "Profile manufacturers", fn: "manufacturerProfiler", params: ["manufacturer_name"] },
      { type: "web_browse", label: "Browse URL", icon: Globe, desc: "Fetch and read any webpage", fn: "webBrowse", params: ["url"] },
    ],
  },
  {
    category: "Communication",
    color: "#ec4899",
    icon: Send,
    desc: "Email, SMS, calls",
    nodes: [
      { type: "send_email", label: "Send Email", icon: Mail, desc: "AI-humanized email outreach", fn: "sendOutreachEmail", params: ["email_id", "auto_humanize"] },
      { type: "send_sms", label: "Send SMS", icon: Phone, desc: "Text via Twilio", fn: "sendSms", params: ["to_phone", "to_name", "message", "auto_generate"] },
      { type: "ai_call", label: "AI Phone Call", icon: PhoneCall, desc: "Automated AI calling", fn: "makeAiCall", params: ["to", "script"] },
      { type: "bulk_email", label: "Bulk Email", icon: Mail, desc: "Mass email campaign", fn: "sendBulkEmails" },
      { type: "gmail", label: "Gmail", icon: Mail, desc: "Gmail send/read", fn: "gmailMessages", params: ["action", "to", "subject", "bodyText"] },
    ],
  },
  {
    category: "Content & Creative",
    color: "#14b8a6",
    icon: Image,
    desc: "Generate proposals, images, video",
    nodes: [
      { type: "generate_proposal", label: "Generate Proposal", icon: FileText, desc: "AI flooring proposal", fn: "generateProposal", params: ["lead_id"] },
      { type: "generate_invoice", label: "Generate Invoice", icon: DollarSign, desc: "Auto invoice generation", fn: "generateInvoice", params: ["proposal_id"] },
      { type: "brand_asset", label: "Brand Asset Generator", icon: Image, desc: "AI images, logos, branding", fn: "generateBrandAsset", params: ["asset_type", "prompt", "style"] },
      { type: "video_script", label: "Video Script", icon: Video, desc: "Video production packages", fn: "aiVideoScript", params: ["video_type", "topic", "duration_seconds", "platform"] },
      { type: "social_media", label: "Social Media Agent", icon: Share2, desc: "Platform content generation", fn: "socialMediaAgent", params: ["action", "platform", "content", "tone"] },
      { type: "seo_analyze", label: "SEO Analysis", icon: TrendingUp, desc: "SEO content and analysis", fn: "seoAnalyze", params: ["url", "keyword"] },
    ],
  },
  {
    category: "Browser & Automation",
    color: "#0ea5e9",
    icon: MousePointer,
    desc: "Browser tasks, scraping, agents",
    nodes: [
      { type: "browser_agent", label: "Browser Agent", icon: MousePointer, desc: "Autonomous browser tasks", fn: "browserAgent", params: ["task_type", "instructions", "target_url"] },
      { type: "agent_runner", label: "Agent Runner", icon: Bot, desc: "Run agent jobs", fn: "agentRunner", params: ["agent_type", "job_description"] },
      { type: "swarm", label: "Swarm Orchestrator", icon: Layers, desc: "Multi-agent swarm execution", fn: "swarmOrchestrator", params: ["command", "targets", "mode"] },
      { type: "process_tasks", label: "Process Agent Tasks", icon: Play, desc: "Process queued tasks", fn: "processAgentTasks" },
    ],
  },
  {
    category: "Integrations",
    color: "#84cc16",
    icon: Link2,
    desc: "External services",
    nodes: [
      { type: "hubspot_sync", label: "HubSpot Sync", icon: Link2, desc: "Sync with HubSpot CRM", fn: "hubspotSync", params: ["action"] },
      { type: "google_drive", label: "Google Drive", icon: Database, desc: "List/import Drive files", fn: "googleDriveFiles" },
      { type: "supabase_query", label: "Supabase Query", icon: Database, desc: "Query Supabase tables", fn: null },
    ],
  },
  {
    category: "Control Flow",
    color: "#64748b",
    icon: GitBranch,
    desc: "Logic, delays, branching",
    nodes: [
      { type: "condition", label: "If / Else", icon: GitBranch, desc: "Conditional branching", fn: null, params: ["field", "operator", "value"] },
      { type: "loop", label: "Loop / For Each", icon: RefreshCcw, desc: "Iterate over a list", fn: null, params: ["source_field"] },
      { type: "delay", label: "Delay / Wait", icon: Clock, desc: "Pause execution", fn: null, params: ["duration", "unit"] },
      { type: "parallel", label: "Parallel Split", icon: MoreHorizontal, desc: "Run multiple branches at once", fn: null },
      { type: "merge", label: "Merge", icon: GitBranch, desc: "Combine parallel branches", fn: null },
      { type: "stop", label: "Stop / End", icon: Pause, desc: "Terminate workflow", fn: null },
      { type: "error_handler", label: "Error Handler", icon: AlertTriangle, desc: "Catch errors and retry or alert", fn: null },
    ],
  },
  {
    category: "Reporting & Output",
    color: "#f97316",
    icon: BarChart3,
    desc: "Reports, exports, notifications",
    nodes: [
      { type: "executive_brief", label: "Executive Brief", icon: FileText, desc: "Morning pipeline brief", fn: "executiveBrief" },
      { type: "report_gen", label: "Report Generator", icon: BarChart3, desc: "Custom analytics report", fn: null },
      { type: "export_csv", label: "Export CSV", icon: ArrowDownToLine, desc: "Export results as CSV", fn: null },
      { type: "notify", label: "Notification", icon: AlertTriangle, desc: "Send alert/notification", fn: null, params: ["channel", "message"] },
      { type: "add_to_entity", label: "Save to Database", icon: Database, desc: "Create/update entity records", fn: null, params: ["entity_name", "fields"] },
    ],
  },
];

// ── Agent Registry ──
export const AGENT_REGISTRY = [
  { id: "xps_assistant", name: "XPS Assistant", desc: "Full-spectrum autonomous AI", icon: Bot, color: "#d4af37", skills: ["CRM", "Leads", "Proposals", "Email", "SMS", "Research", "Knowledge Base", "53 functions"] },
  { id: "admin_operator", name: "Admin Operator", desc: "System admin & infrastructure", icon: Shield, color: "#a855f7", skills: ["User management", "API keys", "System health", "Deployments"] },
  { id: "scraper", name: "Scraper Agent", desc: "Web scraping & data extraction", icon: Globe, color: "#22c55e", skills: ["URL scraping", "Keyword research", "Data extraction", "Change detection"] },
  { id: "lead_gen", name: "Lead Gen Agent", desc: "Lead generation specialist", icon: Users, color: "#f59e0b", skills: ["Lead scraping", "Scoring", "Enrichment", "Pipeline management"] },
  { id: "sales_director", name: "Sales Director", desc: "Sales strategy & outreach", icon: Target, color: "#ec4899", skills: ["Outreach strategy", "Follow-up", "Closing", "CRM"] },
  { id: "social_media", name: "Social Media", desc: "Content & social management", icon: Share2, color: "#8b5cf6", skills: ["Content creation", "Scheduling", "Engagement", "Analytics"] },
  { id: "seo_marketing", name: "SEO & Marketing", desc: "SEO optimization & content", icon: TrendingUp, color: "#06b6d4", skills: ["Keyword analysis", "Content optimization", "Competitor tracking"] },
  { id: "reputation", name: "Reputation Agent", desc: "Review & reputation management", icon: Star, color: "#f97316", skills: ["Review monitoring", "Response generation", "Sentiment analysis"] },
  { id: "prediction", name: "Prediction Agent", desc: "Forecasting & trends", icon: BarChart3, color: "#6366f1", skills: ["Sales forecasting", "Market trends", "Demand prediction"] },
  { id: "simulation", name: "Simulation Agent", desc: "Scenario modeling", icon: Layers, color: "#14b8a6", skills: ["Pricing models", "Market simulation", "What-if analysis"] },
  { id: "validation", name: "Validation Agent", desc: "Data quality & verification", icon: CheckCircle, color: "#84cc16", skills: ["Business validation", "Contact verification", "Data cleaning"] },
  { id: "recommendation", name: "Recommendation Agent", desc: "Product & action recommendations", icon: Sparkles, color: "#d4af37", skills: ["Product matching", "Pricing", "Strategy recommendations"] },
  { id: "billing_controller", name: "Billing Controller", desc: "Invoicing & payments", icon: DollarSign, color: "#ef4444", skills: ["Invoice generation", "Payment tracking", "Reminders"] },
  { id: "code_agent", name: "Code Agent", desc: "Technical automation", icon: Hash, color: "#64748b", skills: ["API integration", "Script generation", "Debugging"] },
  { id: "ceo_orchestrator", name: "CEO Orchestrator", desc: "Multi-agent coordination", icon: Zap, color: "#d4af37", skills: ["Agent delegation", "Priority management", "Swarm control"] },
  { id: "security", name: "Security Agent", desc: "Security & compliance", icon: Shield, color: "#ef4444", skills: ["Audit logging", "Access control", "Threat monitoring"] },
  { id: "maintenance", name: "Maintenance Agent", desc: "System maintenance", icon: Settings, color: "#64748b", skills: ["Data cleanup", "Archive management", "Health checks"] },
];

// ── AI Recommendations ──
export const AI_RECOMMENDATIONS = {
  lead_scraper: "Pair with Lead Scorer → Contact Enricher for a complete pipeline. Best at 10-25 leads per run.",
  bulk_pipeline: "Most powerful lead tool — runs full scrape→score→enrich→research in one step. Use for market expansion.",
  lead_scorer: "Run after any scrape step. Scores 0-100. Follow with Filter (score > 60) to focus outreach.",
  contact_enricher: "Finds decision-maker names, emails, phones. Best used after scoring to enrich top leads only.",
  send_email: "Use auto_humanize=true for AI-refined copy. Pair with a Delay (2-3 days) then Follow-Up email.",
  send_sms: "SMS has 3-5x response rate vs email. Use for hot leads (score > 70). Keep under 160 chars.",
  ai_takeoff: "Generates zone-by-zone material/labor estimates. Required before Generate Bid Package.",
  generate_bid: "Creates branded NCP bid document. Run after AI Takeoff. Auto-includes credentials & warranty.",
  discover_jobs: "Searches SAM.gov, Dodge, BidNet, permit databases. Best when targeting specific project types.",
  web_research: "Use deep_analysis=true for thorough reports. Results auto-save to Knowledge Base.",
  territory_analyzer: "Maps market opportunity by zip code. Great before launching into a new market.",
  condition: "Add after scorer to split: score>70 → hot outreach, 40-70 → nurture, <40 → archive.",
  delay: "Critical between outreach touches. Best practice: 2 days after initial, 5 days for follow-up #2.",
  swarm: "Launches multiple agents simultaneously. Use for overnight batch operations across markets.",
  executive_brief: "Auto-generates morning brief with pipeline stats, new leads, pending bids. Schedule daily.",
  browser_agent: "Autonomous web tasks — form filling, social engagement, research. Specify clear instructions.",
  generate_proposal: "AI-generates full flooring proposal with pricing, scope, timeline. Requires lead_id.",
  social_media: "Creates platform-specific content. Use content calendar action for weekly planning.",
  hubspot_sync: "Bidirectional CRM sync. Run after lead processing to keep HubSpot current.",
  competitor_scrape: "Extracts pricing, services, reviews from competitor sites. Feeds into knowledge base.",
};

export default NODE_REGISTRY;