import {
  Search, Users, Star, Mail, Phone, Brain, Target, Globe,
  Building2, FileText, BarChart3, TrendingUp, Briefcase,
  Send, Clock, Bot, Layers, DollarSign, Image, Video,
  Share2, Database, Map, Zap, Shield, RefreshCcw,
  BookOpen, Upload, CalendarDays, Link2, Hash, Sparkles
} from "lucide-react";

/*
  50 production-ready workflow templates for XPS.
  Each maps to real backend functions, agents, Groq, Google Workspace, Twilio, HeyGen, etc.
  Every template includes: projected_result, schedule suggestion, linked_tools, and category.
*/

const WORKFLOW_TEMPLATES_50 = [
  // ── LEAD GENERATION (1-8) ──
  {
    id: "wf_01", name: "FL Lead Blitz", category: "Lead Gen", icon: Search, color: "#d4af37",
    description: "Scrape 50 epoxy contractor leads in Florida, score, enrich contacts, auto-email top 20.",
    projected_result: "~20 qualified leads/week, 3-5 responses, $15K-$40K pipeline value",
    trigger: "Schedule", schedule: "Weekly Mon 6am",
    linked_tools: ["leadScraper", "leadScorer", "contactEnricher", "sendOutreachEmail", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Monday 6am" },
      { type: "lead_scraper", label: "Scrape FL Epoxy Contractors", config: { location: "Florida", industry: "epoxy flooring", count: 50 } },
      { type: "lead_scorer", label: "AI Score All Leads", config: { batch_all: true, min_score: 0 } },
      { type: "filter_leads", label: "Filter Score > 60", config: { field: "score", operator: ">", value: 60 } },
      { type: "contact_enricher", label: "Enrich Top Leads" },
      { type: "send_email", label: "Auto Email Top 20", config: { auto_humanize: true } },
      { type: "notify", label: "Slack/SMS Summary" },
    ],
  },
  {
    id: "wf_02", name: "Multi-State Pipeline Builder", category: "Lead Gen", icon: Layers, color: "#22c55e",
    description: "Bulk pipeline across FL, TX, AZ — scrape, score, enrich, research top prospects.",
    projected_result: "75+ leads across 3 states, $50K-$120K pipeline/month",
    trigger: "Schedule", schedule: "Weekly Mon 5am",
    linked_tools: ["bulkLeadPipeline", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Monday 5am" },
      { type: "bulk_pipeline", label: "FL Pipeline", config: { locations: ["Florida"], count_per_location: 25, industry: "epoxy flooring" } },
      { type: "bulk_pipeline", label: "TX Pipeline", config: { locations: ["Texas"], count_per_location: 25, industry: "epoxy flooring" } },
      { type: "bulk_pipeline", label: "AZ Pipeline", config: { locations: ["Arizona"], count_per_location: 25, industry: "epoxy flooring" } },
      { type: "executive_brief", label: "Pipeline Summary Report" },
    ],
  },
  {
    id: "wf_03", name: "XPress Daily Scraper", category: "Lead Gen", icon: Target, color: "#f59e0b",
    description: "Daily AZ contractor lead scraping for XPS Xpress material sales.",
    projected_result: "10-15 new material leads/day, $5K-$10K monthly material orders",
    trigger: "Schedule", schedule: "Daily 7am",
    linked_tools: ["xpressLeadScraper", "leadScorer", "sendSms"],
    steps: [
      { type: "trigger_schedule", label: "Daily 7am" },
      { type: "xpress_scraper", label: "XPress AZ Scrape", config: { count: 15 } },
      { type: "lead_scorer", label: "Score New Leads" },
      { type: "filter_leads", label: "Hot Leads Only (>70)" },
      { type: "send_sms", label: "Text Alert to Sales", config: { auto_generate: true } },
    ],
  },
  {
    id: "wf_04", name: "Registry Scraper — 10 States", category: "Lead Gen", icon: Building2, color: "#8b5cf6",
    description: "Scrape state business registries for new flooring companies across 10 states.",
    projected_result: "200+ new company records/month, expand addressable market 40%",
    trigger: "Schedule", schedule: "Monthly 1st 3am",
    linked_tools: ["registryScraper", "validateAndEnrichLead"],
    steps: [
      { type: "trigger_schedule", label: "Monthly 1st" },
      { type: "registry_scraper", label: "Scrape 10 State Registries", config: { states: ["FL","TX","AZ","OH","CA","GA","NC","TN","PA","IL"], batch_size: 20 } },
      { type: "validate_enrich", label: "Validate & Enrich All" },
      { type: "lead_scorer", label: "Score New Records" },
      { type: "notify", label: "Monthly Registry Report" },
    ],
  },
  {
    id: "wf_05", name: "Jobs Lead Hunter", category: "Lead Gen", icon: Briefcase, color: "#06b6d4",
    description: "Find end-buyer job leads (restaurants, gyms, warehouses) needing floor coatings.",
    projected_result: "15-20 job leads/week, avg $8K-$25K per project",
    trigger: "Schedule", schedule: "Twice weekly",
    linked_tools: ["jobsLeadScraper", "contactEnricher"],
    steps: [
      { type: "trigger_schedule", label: "Tue & Thu 8am" },
      { type: "jobs_scraper", label: "Scrape Job Leads", config: { count: 20 } },
      { type: "contact_enricher", label: "Find Decision Makers" },
      { type: "lead_scorer", label: "Score & Prioritize" },
      { type: "send_email", label: "Intro Email to Top 10" },
    ],
  },
  {
    id: "wf_06", name: "Custom Keyword Scraper", category: "Lead Gen", icon: Hash, color: "#ec4899",
    description: "Scrape leads by custom keywords — garage floor, metallic epoxy, polyaspartic.",
    projected_result: "Niche-targeted leads with 2x higher conversion rate",
    trigger: "Manual",
    linked_tools: ["customScraper", "leadScorer"],
    steps: [
      { type: "trigger_manual", label: "Manual Run" },
      { type: "custom_scraper", label: "Custom Keyword Scrape", config: { keywords: "metallic epoxy,garage floor coating,polyaspartic", count: 30 } },
      { type: "lead_scorer", label: "AI Score Results" },
      { type: "contact_enricher", label: "Enrich Winners" },
    ],
  },
  {
    id: "wf_07", name: "Dormant Lead Re-Engager", category: "Lead Gen", icon: RefreshCcw, color: "#f97316",
    description: "Find leads not contacted in 30+ days, re-score, and send personalized follow-ups.",
    projected_result: "Recover 10-15% of cold leads, $20K+ in revived pipeline",
    trigger: "Schedule", schedule: "Weekly Fri 9am",
    linked_tools: ["dormantReengager", "sendOutreachEmail", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Friday 9am" },
      { type: "filter_leads", label: "Find Stale Leads (30+ days)" },
      { type: "lead_scorer", label: "Re-Score" },
      { type: "deep_research", label: "Quick Research Update" },
      { type: "send_email", label: "Personalized Re-Engage Email" },
    ],
  },
  {
    id: "wf_08", name: "Territory Expansion Scanner", category: "Lead Gen", icon: Map, color: "#14b8a6",
    description: "Analyze 5 new cities for market opportunity before launching lead gen there.",
    projected_result: "Data-driven market entry — avoid wasted ad spend in low-potential areas",
    trigger: "Manual",
    linked_tools: ["territoryAnalyzer", "competitorScrape"],
    steps: [
      { type: "trigger_manual", label: "Manual" },
      { type: "territory_analyzer", label: "Analyze Tampa", config: { city: "Tampa", state: "FL" } },
      { type: "territory_analyzer", label: "Analyze Dallas", config: { city: "Dallas", state: "TX" } },
      { type: "territory_analyzer", label: "Analyze Phoenix", config: { city: "Phoenix", state: "AZ" } },
      { type: "competitor_scrape", label: "Competitor Landscape" },
      { type: "executive_brief", label: "Territory Report" },
    ],
  },

  // ── SALES & OUTREACH (9-16) ──
  {
    id: "wf_09", name: "Email Drip — 3 Touch", category: "Sales", icon: Mail, color: "#ec4899",
    description: "3-email drip sequence: intro → value prop → call-to-action with delays.",
    projected_result: "25-35% open rate, 8-12% response rate, 3-5 meetings/batch",
    trigger: "Manual",
    linked_tools: ["sendOutreachEmail", "groqSmartRouter"],
    steps: [
      { type: "trigger_manual", label: "Start Drip" },
      { type: "send_email", label: "Email 1: Introduction", config: { auto_humanize: true } },
      { type: "delay", label: "Wait 2 Days", config: { duration: 2, unit: "days" } },
      { type: "send_email", label: "Email 2: Case Study" },
      { type: "delay", label: "Wait 3 Days", config: { duration: 3, unit: "days" } },
      { type: "send_email", label: "Email 3: CTA + Offer" },
    ],
  },
  {
    id: "wf_10", name: "SMS + Email Combo Blast", category: "Sales", icon: Phone, color: "#22c55e",
    description: "Text hot leads first, then follow up with detailed email 2 hours later.",
    projected_result: "SMS gets 45% read rate — combo drives 2x more responses than email alone",
    trigger: "Manual",
    linked_tools: ["sendSms", "sendOutreachEmail", "groqSmartRouter"],
    steps: [
      { type: "trigger_manual", label: "Start" },
      { type: "filter_leads", label: "Hot Leads (Score > 70)" },
      { type: "send_sms", label: "Quick Text Intro" },
      { type: "delay", label: "Wait 2 Hours", config: { duration: 2, unit: "hours" } },
      { type: "send_email", label: "Detailed Follow-Up Email" },
    ],
  },
  {
    id: "wf_11", name: "WhatsApp Outreach Engine", category: "Sales", icon: Send, color: "#25D366",
    description: "Score leads, craft personalized WhatsApp messages via Twilio for warm prospects.",
    projected_result: "WhatsApp 70%+ open rate — highest engagement channel",
    trigger: "Schedule", schedule: "Daily 10am",
    linked_tools: ["twilioMessenger", "leadScorer", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Daily 10am" },
      { type: "filter_leads", label: "Warm Leads (Score 50-70)" },
      { type: "send_sms", label: "WhatsApp Message via Twilio" },
      { type: "notify", label: "Log Outreach Activity" },
    ],
  },
  {
    id: "wf_12", name: "AI Call Prep + Dial", category: "Sales", icon: Phone, color: "#6366f1",
    description: "Research the lead, generate a call script with Groq, then trigger AI call.",
    projected_result: "Prepared calls close 3x more — AI handles initial screening",
    trigger: "Manual",
    linked_tools: ["deepResearch", "groqSmartRouter", "makeAiCall"],
    steps: [
      { type: "trigger_manual", label: "Select Lead" },
      { type: "deep_research", label: "Company Research" },
      { type: "ai_call", label: "AI Phone Call", config: { script: "auto" } },
      { type: "notify", label: "Log Call Result" },
    ],
  },
  {
    id: "wf_13", name: "Proposal Auto-Generator", category: "Sales", icon: FileText, color: "#d4af37",
    description: "Generate branded flooring proposal, email to lead, schedule follow-up.",
    projected_result: "Cut proposal time from 2hrs to 5min — increase close rate 20%",
    trigger: "Manual",
    linked_tools: ["generateProposal", "sendOutreachEmail"],
    steps: [
      { type: "trigger_manual", label: "Select Lead" },
      { type: "generate_proposal", label: "AI Generate Proposal" },
      { type: "send_email", label: "Email Proposal to Lead" },
      { type: "delay", label: "Wait 3 Days" },
      { type: "send_email", label: "Follow-Up: Review Proposal?" },
    ],
  },
  {
    id: "wf_14", name: "Stale Pipeline Nurture", category: "Sales", icon: Clock, color: "#f59e0b",
    description: "Auto-detect leads stuck in pipeline > 14 days, re-engage with new angle.",
    projected_result: "Move 15-25% of stuck deals forward, recover $30K+ pipeline",
    trigger: "Schedule", schedule: "Weekly Wed 8am",
    linked_tools: ["dormantReengager", "groqSmartRouter", "sendOutreachEmail"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Wed 8am" },
      { type: "filter_leads", label: "Stuck > 14 Days" },
      { type: "deep_research", label: "Refresh Intel" },
      { type: "send_email", label: "New Angle Email" },
      { type: "send_sms", label: "Soft Touch SMS" },
    ],
  },
  {
    id: "wf_15", name: "Invoice & Payment Follow-Up", category: "Sales", icon: DollarSign, color: "#ef4444",
    description: "Generate invoice after job completion, email client, follow up at 7, 14, 30 days.",
    projected_result: "Reduce AR aging from 45 to 22 days avg, improve cash flow 30%",
    trigger: "Manual",
    linked_tools: ["generateInvoice", "sendOutreachEmail"],
    steps: [
      { type: "trigger_manual", label: "Job Complete" },
      { type: "generate_invoice", label: "Generate Invoice" },
      { type: "send_email", label: "Send Invoice Email" },
      { type: "delay", label: "Wait 7 Days" },
      { type: "send_email", label: "Payment Reminder 1" },
      { type: "delay", label: "Wait 7 Days" },
      { type: "send_email", label: "Payment Reminder 2" },
    ],
  },
  {
    id: "wf_16", name: "Sentiment-Based Outreach", category: "Sales", icon: Brain, color: "#8b5cf6",
    description: "Analyze lead sentiment from past interactions, adjust outreach tone accordingly.",
    projected_result: "Sentiment-matched messaging increases response rate 40%",
    trigger: "Manual",
    linked_tools: ["sentimentAnalyst", "groqSmartRouter", "sendOutreachEmail"],
    steps: [
      { type: "trigger_manual", label: "Select Batch" },
      { type: "filter_leads", label: "Contacted Leads" },
      { type: "web_research", label: "Sentiment Analysis" },
      { type: "send_email", label: "Tone-Matched Email" },
    ],
  },

  // ── BIDDING & COMMERCIAL (17-24) ──
  {
    id: "wf_17", name: "Gov Bid Discovery → Auto Bid", category: "Bidding", icon: Briefcase, color: "#22c55e",
    description: "Discover SAM.gov/BidNet opportunities, AI takeoff, generate & send bid package.",
    projected_result: "5-10 bids/month, 20% win rate = $200K-$500K new contracts/year",
    trigger: "Schedule", schedule: "Daily 6am",
    linked_tools: ["discoverBidJobs", "aiTakeoff", "generateBidPackage"],
    steps: [
      { type: "trigger_schedule", label: "Daily 6am" },
      { type: "discover_jobs", label: "Scan Gov Bid Sources", config: { states: ["FL","TX","AZ"], sector: "Government Federal" } },
      { type: "ai_takeoff", label: "AI Cost Estimation" },
      { type: "generate_bid", label: "Generate Bid Package" },
      { type: "notify", label: "Alert: New Bids Ready for Review" },
    ],
  },
  {
    id: "wf_18", name: "GC Outreach Blitz", category: "Bidding", icon: Building2, color: "#d4af37",
    description: "Scrape general contractors, profile them, send branded intro packages.",
    projected_result: "Build GC rolodex of 100+ contacts, 5-10 sub opportunities/quarter",
    trigger: "Schedule", schedule: "Bi-weekly",
    linked_tools: ["scrapeContractors", "sendIntroPackage", "generateCompanyPackage"],
    steps: [
      { type: "trigger_schedule", label: "Bi-weekly Mon" },
      { type: "scrape_contractors", label: "Find GCs in FL, TX", config: { states: ["FL","TX"], contractor_type: "general", limit: 25 } },
      { type: "contact_enricher", label: "Find Estimators/PMs" },
      { type: "send_intro", label: "Send Intro Package" },
      { type: "delay", label: "Wait 5 Days" },
      { type: "send_email", label: "Follow-Up Email" },
    ],
  },
  {
    id: "wf_19", name: "Commercial Permit Monitor", category: "Bidding", icon: Shield, color: "#6366f1",
    description: "Monitor permit databases for new commercial construction, auto-create job records.",
    projected_result: "Catch projects 4-8 weeks before competitors, first-mover advantage",
    trigger: "Schedule", schedule: "Daily 5am",
    linked_tools: ["discoverBidJobs", "deepResearch"],
    steps: [
      { type: "trigger_schedule", label: "Daily 5am" },
      { type: "discover_jobs", label: "Scan Permit DBs", config: { states: ["FL","TX","AZ","OH"], source_type: "Permit DB" } },
      { type: "deep_research", label: "Research Each Project" },
      { type: "add_to_entity", label: "Save to CommercialJob DB" },
      { type: "notify", label: "New Permits Alert" },
    ],
  },
  {
    id: "wf_20", name: "Bid Follow-Up Machine", category: "Bidding", icon: Send, color: "#f59e0b",
    description: "Track submitted bids, auto follow-up at 3, 7, 14 days with escalating urgency.",
    projected_result: "Increase bid win rate 15% through persistent follow-up",
    trigger: "Schedule", schedule: "Daily 9am",
    linked_tools: ["sendOutreachEmail", "sendSms"],
    steps: [
      { type: "trigger_schedule", label: "Daily 9am" },
      { type: "filter_leads", label: "Bids Awaiting Response" },
      { type: "condition", label: "Check Days Since Sent" },
      { type: "send_email", label: "Follow-Up Email" },
      { type: "send_sms", label: "SMS at Day 14+" },
    ],
  },
  {
    id: "wf_21", name: "Architect Relationship Builder", category: "Bidding", icon: Users, color: "#14b8a6",
    description: "Find architects specifying flooring, send portfolio + schedule coffee meeting.",
    projected_result: "Get spec'd into 3-5 projects/quarter worth $100K+ each",
    trigger: "Monthly",
    linked_tools: ["scrapeContractors", "sendOutreachEmail", "generateCompanyPackage"],
    steps: [
      { type: "trigger_schedule", label: "Monthly 1st" },
      { type: "scrape_contractors", label: "Find Architects", config: { contractor_type: "architect", limit: 20 } },
      { type: "contact_enricher", label: "Find Principals" },
      { type: "brand_asset", label: "Generate Portfolio PDF" },
      { type: "send_email", label: "Architect Intro + Portfolio" },
    ],
  },
  {
    id: "wf_22", name: "Competitive Bid Pricing", category: "Bidding", icon: DollarSign, color: "#ef4444",
    description: "Research competitor pricing before submitting bids to optimize your price point.",
    projected_result: "Price 10-15% more competitively, increase win rate without sacrificing margin",
    trigger: "Manual",
    linked_tools: ["competitorScrape", "dynamicPricing", "groqSmartRouter"],
    steps: [
      { type: "trigger_manual", label: "Before Bid Submission" },
      { type: "competitor_scrape", label: "Scrape Competitor Pricing" },
      { type: "web_research", label: "Market Rate Research" },
      { type: "ai_takeoff", label: "Recalculate with Intel" },
      { type: "notify", label: "Pricing Recommendation" },
    ],
  },
  {
    id: "wf_23", name: "Subcontractor Database Builder", category: "Bidding", icon: Database, color: "#84cc16",
    description: "Build a database of reliable subcontractors by trade across target states.",
    projected_result: "Ready-to-deploy crew list for any project type in any market",
    trigger: "Monthly",
    linked_tools: ["populateContractorDB", "contactEnricher"],
    steps: [
      { type: "trigger_schedule", label: "Monthly 15th" },
      { type: "scrape_contractors", label: "Scrape Subs FL", config: { states: ["FL"], contractor_type: "subcontractor", limit: 50 } },
      { type: "scrape_contractors", label: "Scrape Subs TX", config: { states: ["TX"], contractor_type: "subcontractor", limit: 50 } },
      { type: "contact_enricher", label: "Enrich Contact Info" },
      { type: "add_to_entity", label: "Save to Contractor DB" },
    ],
  },
  {
    id: "wf_24", name: "Bid Result Tracker", category: "Bidding", icon: BarChart3, color: "#0ea5e9",
    description: "Track bid outcomes, analyze win/loss patterns, adjust strategy.",
    projected_result: "Data-driven bid strategy improves win rate 10-20% over 6 months",
    trigger: "Schedule", schedule: "Weekly Fri 4pm",
    linked_tools: ["bidResultsScraper", "executiveBrief"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Fri 4pm" },
      { type: "filter_leads", label: "This Week's Bid Outcomes" },
      { type: "web_research", label: "Analyze Win/Loss Patterns" },
      { type: "executive_brief", label: "Bid Performance Report" },
      { type: "notify", label: "Send to Sales Team" },
    ],
  },

  // ── MARKETING & CONTENT (25-32) ──
  {
    id: "wf_25", name: "Weekly Blog Machine", category: "Marketing", icon: FileText, color: "#8b5cf6",
    description: "Research trending topics, generate SEO blog post, publish to Google Docs.",
    projected_result: "4 SEO blog posts/month, 500+ organic visitors/month after 3 months",
    trigger: "Schedule", schedule: "Weekly Mon 7am",
    linked_tools: ["seoAnalyze", "groqSmartRouter", "googleDriveFiles"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Monday 7am" },
      { type: "seo_analyze", label: "Research Trending Keywords" },
      { type: "web_research", label: "Gather Topic Data" },
      { type: "social_media", label: "Generate Blog Post", config: { action: "create", platform: "blog" } },
      { type: "google_drive", label: "Save to Google Docs" },
      { type: "notify", label: "Blog Ready for Review" },
    ],
  },
  {
    id: "wf_26", name: "Social Media Content Factory", category: "Marketing", icon: Share2, color: "#ec4899",
    description: "Generate 7 days of social content across LinkedIn, Instagram, Facebook.",
    projected_result: "Consistent daily posting = 3x brand visibility, 200+ followers/month",
    trigger: "Schedule", schedule: "Weekly Sun 8pm",
    linked_tools: ["socialMediaAgent", "generateBrandAsset", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Sunday 8pm" },
      { type: "social_media", label: "LinkedIn Posts x7", config: { platform: "linkedin", tone: "professional" } },
      { type: "social_media", label: "Instagram Posts x7", config: { platform: "instagram", tone: "visual" } },
      { type: "brand_asset", label: "Generate Post Images" },
      { type: "google_drive", label: "Save Content Calendar" },
    ],
  },
  {
    id: "wf_27", name: "Video Script + HeyGen Avatar", category: "Marketing", icon: Video, color: "#06b6d4",
    description: "Generate video script about XPS products, create HeyGen avatar video.",
    projected_result: "Professional product videos at $0 production cost, 5K+ views/video",
    trigger: "Manual",
    linked_tools: ["aiVideoScript", "heygenAvatar", "groqSmartRouter"],
    steps: [
      { type: "trigger_manual", label: "Start" },
      { type: "video_script", label: "Generate Script", config: { video_type: "product_demo", duration_seconds: 60 } },
      { type: "browser_agent", label: "Create HeyGen Video" },
      { type: "social_media", label: "Post to YouTube + LinkedIn" },
    ],
  },
  {
    id: "wf_28", name: "Competitor Content Spy", category: "Marketing", icon: Globe, color: "#f97316",
    description: "Monitor competitor websites and social media for new content, pricing changes.",
    projected_result: "Always know what competitors are doing — react within 24hrs",
    trigger: "Schedule", schedule: "Daily 6am",
    linked_tools: ["competitorMonitor", "competitorScrape", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Daily 6am" },
      { type: "competitor_scrape", label: "Scan Top 5 Competitors" },
      { type: "web_research", label: "Analyze Changes" },
      { type: "notify", label: "Competitor Alert" },
    ],
  },
  {
    id: "wf_29", name: "SEO Keyword Domination", category: "SEO", icon: TrendingUp, color: "#22c55e",
    description: "Analyze top 50 epoxy keywords, find gaps, generate optimized content.",
    projected_result: "Rank page 1 for 10+ keywords within 6 months",
    trigger: "Schedule", schedule: "Monthly",
    linked_tools: ["seoAnalyze", "knowledgeScraper", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Monthly 1st" },
      { type: "seo_analyze", label: "Audit Current Rankings" },
      { type: "web_research", label: "Competitor Keyword Research" },
      { type: "social_media", label: "Generate 5 SEO Articles" },
      { type: "google_drive", label: "Save to Content Folder" },
    ],
  },
  {
    id: "wf_30", name: "Review Response Bot", category: "Marketing", icon: Star, color: "#d4af37",
    description: "Monitor Google/Yelp reviews, auto-generate professional responses.",
    projected_result: "100% review response rate builds trust, improves local SEO ranking",
    trigger: "Schedule", schedule: "Daily 8am",
    linked_tools: ["webBrowse", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Daily 8am" },
      { type: "web_browse", label: "Check Google Reviews" },
      { type: "web_research", label: "Analyze Sentiment" },
      { type: "notify", label: "Drafted Responses for Approval" },
    ],
  },
  {
    id: "wf_31", name: "Email Newsletter Generator", category: "Marketing", icon: Mail, color: "#6366f1",
    description: "Compile this week's projects, wins, and tips into a newsletter for leads.",
    projected_result: "Stay top-of-mind with 500+ contacts, 2-3 inbound inquiries/month",
    trigger: "Schedule", schedule: "Weekly Fri 2pm",
    linked_tools: ["groqSmartRouter", "sendBulkEmails", "gmailMessages"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Fri 2pm" },
      { type: "web_research", label: "Compile Weekly Highlights" },
      { type: "social_media", label: "Draft Newsletter" },
      { type: "bulk_email", label: "Send to Mailing List" },
    ],
  },
  {
    id: "wf_32", name: "Brand Asset Generator", category: "Marketing", icon: Image, color: "#14b8a6",
    description: "Generate social banners, email headers, and ad creatives for campaigns.",
    projected_result: "Professional branded visuals without a designer — save $2K/month",
    trigger: "Manual",
    linked_tools: ["generateBrandAsset", "googleDriveFiles"],
    steps: [
      { type: "trigger_manual", label: "Start" },
      { type: "brand_asset", label: "Social Banner", config: { asset_type: "social_banner" } },
      { type: "brand_asset", label: "Email Header", config: { asset_type: "email_header" } },
      { type: "brand_asset", label: "Ad Creative", config: { asset_type: "ad_creative" } },
      { type: "google_drive", label: "Save to Brand Folder" },
    ],
  },

  // ── RESEARCH & INTELLIGENCE (33-38) ──
  {
    id: "wf_33", name: "Deep Company Intel Report", category: "Research", icon: Brain, color: "#8b5cf6",
    description: "Full multi-source intelligence report on any target company.",
    projected_result: "Know everything about a prospect before first contact — close faster",
    trigger: "Manual",
    linked_tools: ["deepResearch", "competitorScrape", "webResearch", "groqSmartRouter"],
    steps: [
      { type: "trigger_manual", label: "Enter Company" },
      { type: "deep_research", label: "Full Company Profile" },
      { type: "competitor_scrape", label: "Their Competitors" },
      { type: "web_research", label: "News & Reviews" },
      { type: "executive_brief", label: "Intel Report" },
    ],
  },
  {
    id: "wf_34", name: "Market Trend Scanner", category: "Research", icon: TrendingUp, color: "#06b6d4",
    description: "Scan industry news, price changes, material trends weekly.",
    projected_result: "Early trend detection = adjust pricing & strategy before competitors",
    trigger: "Schedule", schedule: "Weekly Mon 5am",
    linked_tools: ["webResearch", "knowledgeScraper", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Mon 5am" },
      { type: "web_research", label: "Epoxy Industry News" },
      { type: "web_research", label: "Material Price Trends" },
      { type: "web_research", label: "Construction Market Data" },
      { type: "knowledge_scraper", label: "Save to Knowledge Base" },
      { type: "executive_brief", label: "Trend Report" },
    ],
  },
  {
    id: "wf_35", name: "Manufacturer Intel Sweep", category: "Research", icon: Building2, color: "#84cc16",
    description: "Profile top 20 epoxy manufacturers — products, pricing, dealer programs.",
    projected_result: "Best supplier deals, know competitor product lines inside-out",
    trigger: "Quarterly",
    linked_tools: ["manufacturerProfiler", "knowledgeScraper"],
    steps: [
      { type: "trigger_schedule", label: "Quarterly" },
      { type: "manufacturer_profiler", label: "Profile Top 20 Manufacturers" },
      { type: "web_research", label: "Pricing & Programs" },
      { type: "knowledge_scraper", label: "Save Intel" },
      { type: "notify", label: "Manufacturer Report Ready" },
    ],
  },
  {
    id: "wf_36", name: "Knowledge Base Auto-Feeder", category: "Research", icon: BookOpen, color: "#f59e0b",
    description: "Scrape 10 industry URLs daily and feed clean data into knowledge base.",
    projected_result: "Ever-growing AI knowledge = smarter proposals, emails, and recommendations",
    trigger: "Schedule", schedule: "Daily 3am",
    linked_tools: ["knowledgeScraper", "knowledgeBulkScraper"],
    steps: [
      { type: "trigger_schedule", label: "Daily 3am" },
      { type: "knowledge_scraper", label: "Scrape Industry Sites", config: { category: "Industry Data" } },
      { type: "knowledge_scraper", label: "Scrape Product Sites", config: { category: "Product Info" } },
      { type: "notify", label: "KB Updated: +X Records" },
    ],
  },
  {
    id: "wf_37", name: "Patent & Innovation Tracker", category: "Research", icon: Zap, color: "#d4af37",
    description: "Monitor patent filings and new products in coatings industry.",
    projected_result: "First to know about new technologies — stay ahead of innovation curve",
    trigger: "Schedule", schedule: "Weekly",
    linked_tools: ["webResearch", "knowledgeScraper", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Thu" },
      { type: "web_research", label: "Patent Search: Epoxy Coatings" },
      { type: "web_research", label: "New Product Launches" },
      { type: "knowledge_scraper", label: "Save Findings" },
      { type: "notify", label: "Innovation Alert" },
    ],
  },
  {
    id: "wf_38", name: "Google Sheets → CRM Sync", category: "Integrations", icon: Link2, color: "#22c55e",
    description: "Pull new rows from Google Sheets, create leads, score and assign.",
    projected_result: "Zero manual data entry — leads flow automatically from any sheet source",
    trigger: "Schedule", schedule: "Every 30min",
    linked_tools: ["googleDriveFiles", "leadScorer"],
    steps: [
      { type: "trigger_schedule", label: "Every 30 Minutes" },
      { type: "google_drive", label: "Read New Sheet Rows" },
      { type: "add_to_entity", label: "Create Lead Records" },
      { type: "lead_scorer", label: "Score New Leads" },
      { type: "notify", label: "New Leads Imported" },
    ],
  },

  // ── OPERATIONS & REPORTING (39-44) ──
  {
    id: "wf_39", name: "Morning CEO Briefing", category: "Reporting", icon: BarChart3, color: "#d4af37",
    description: "Auto-generate morning briefing: pipeline stats, new leads, pending bids, cash flow.",
    projected_result: "Start every day with full business awareness in 30 seconds",
    trigger: "Schedule", schedule: "Daily 7am",
    linked_tools: ["executiveBrief", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Daily 7am" },
      { type: "executive_brief", label: "Generate Full Brief" },
      { type: "send_email", label: "Email to Owner" },
      { type: "send_sms", label: "SMS Key Metrics" },
    ],
  },
  {
    id: "wf_40", name: "Overnight System Healer", category: "Operations", icon: Shield, color: "#ef4444",
    description: "Run system health check, clean stale data, optimize DB, fix broken records.",
    projected_result: "99.9% system uptime, zero data rot, always-clean database",
    trigger: "Schedule", schedule: "Daily 2am",
    linked_tools: ["nightlyAutoHeal", "autoHealSystem"],
    steps: [
      { type: "trigger_schedule", label: "Daily 2am" },
      { type: "process_tasks", label: "Process Queued Tasks" },
      { type: "browser_agent", label: "System Health Check" },
      { type: "notify", label: "Overnight Report" },
    ],
  },
  {
    id: "wf_41", name: "HubSpot Bi-Directional Sync", category: "Integrations", icon: Link2, color: "#ff7a59",
    description: "Sync leads, deals, and contacts between XPS and HubSpot CRM.",
    projected_result: "Single source of truth across both systems, zero duplicate effort",
    trigger: "Schedule", schedule: "Every 2 hours",
    linked_tools: ["hubspotSync"],
    steps: [
      { type: "trigger_schedule", label: "Every 2 Hours" },
      { type: "hubspot_sync", label: "Push New Leads to HubSpot" },
      { type: "hubspot_sync", label: "Pull Updates from HubSpot" },
      { type: "dedup", label: "Deduplicate Records" },
    ],
  },
  {
    id: "wf_42", name: "Google Calendar Job Scheduler", category: "Operations", icon: CalendarDays, color: "#4285f4",
    description: "When a bid is won, auto-create job milestones in Google Calendar.",
    projected_result: "Never miss a deadline — automatic project scheduling",
    trigger: "Event",
    linked_tools: ["googleDriveFiles"],
    steps: [
      { type: "trigger_new_lead", label: "Bid Marked as Won" },
      { type: "web_research", label: "Calculate Timeline" },
      { type: "browser_agent", label: "Create Calendar Events" },
      { type: "send_email", label: "Notify Project Team" },
    ],
  },
  {
    id: "wf_43", name: "Weekly P&L Reporter", category: "Finance", icon: DollarSign, color: "#22c55e",
    description: "Compile weekly revenue, expenses, profit margin from jobs and invoices.",
    projected_result: "Real-time financial visibility — catch margin problems early",
    trigger: "Schedule", schedule: "Weekly Fri 5pm",
    linked_tools: ["executiveBrief", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Fri 5pm" },
      { type: "web_research", label: "Compile Financial Data" },
      { type: "executive_brief", label: "P&L Summary" },
      { type: "google_drive", label: "Save to Finance Folder" },
      { type: "send_email", label: "Email to Owner" },
    ],
  },
  {
    id: "wf_44", name: "Project Photo → Drive Backup", category: "Operations", icon: Upload, color: "#0ea5e9",
    description: "Auto-backup all new site photos to organized Google Drive folders.",
    projected_result: "Never lose a project photo — organized by job, date, zone",
    trigger: "Schedule", schedule: "Daily 11pm",
    linked_tools: ["googleDriveFiles"],
    steps: [
      { type: "trigger_schedule", label: "Daily 11pm" },
      { type: "filter_leads", label: "Jobs with New Photos" },
      { type: "google_drive", label: "Upload to Drive Folders" },
      { type: "notify", label: "Backup Complete" },
    ],
  },

  // ── ADVANCED & AUTOMATION (45-50) ──
  {
    id: "wf_45", name: "Multi-Agent Swarm — Market Blitz", category: "Operations", icon: Bot, color: "#d4af37",
    description: "Deploy 5 agents simultaneously: scrape, research, score, email, and report.",
    projected_result: "10x throughput — what takes a team a week done in 30 minutes",
    trigger: "Manual",
    linked_tools: ["swarmOrchestrator", "groqSmartRouter"],
    steps: [
      { type: "trigger_manual", label: "Launch Swarm" },
      { type: "swarm", label: "Deploy 5-Agent Swarm", config: { mode: "parallel", targets: ["FL","TX","AZ"] } },
      { type: "executive_brief", label: "Swarm Results Report" },
      { type: "notify", label: "Swarm Complete" },
    ],
  },
  {
    id: "wf_46", name: "Full Client Onboarding", category: "Operations", icon: Users, color: "#14b8a6",
    description: "New client won → create project, schedule kickoff, generate docs, set up portal.",
    projected_result: "Professional onboarding in 5 minutes instead of 2 hours",
    trigger: "Manual",
    linked_tools: ["generateProposal", "sendOutreachEmail", "googleDriveFiles"],
    steps: [
      { type: "trigger_manual", label: "Client Won" },
      { type: "add_to_entity", label: "Create Project Record" },
      { type: "generate_proposal", label: "Generate SOW Document" },
      { type: "browser_agent", label: "Create Google Drive Folder" },
      { type: "send_email", label: "Welcome Email + Portal Link" },
      { type: "notify", label: "Onboarding Complete" },
    ],
  },
  {
    id: "wf_47", name: "Auto-Enhance Everything", category: "Operations", icon: Sparkles, color: "#8b5cf6",
    description: "Run AI enhancer across all tools, agents, and workflows to optimize performance.",
    projected_result: "Continuous self-improvement — system gets smarter every week",
    trigger: "Schedule", schedule: "Weekly Sun 1am",
    linked_tools: ["autoEnhanceTools", "hyperEvolver", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Weekly Sun 1am" },
      { type: "browser_agent", label: "Run Auto-Enhance" },
      { type: "process_tasks", label: "Process Improvements" },
      { type: "notify", label: "Enhancement Report" },
    ],
  },
  {
    id: "wf_48", name: "Supabase Data Sync", category: "Integrations", icon: Database, color: "#3ECF8E",
    description: "Sync key entities to Supabase for external apps, dashboards, or mobile access.",
    projected_result: "Real-time data available to any external tool or custom app",
    trigger: "Schedule", schedule: "Every 15 min",
    linked_tools: ["supabaseAdmin"],
    steps: [
      { type: "trigger_schedule", label: "Every 15 Minutes" },
      { type: "add_to_entity", label: "Export Leads to Supabase" },
      { type: "add_to_entity", label: "Export Jobs to Supabase" },
      { type: "notify", label: "Sync Complete" },
    ],
  },
  {
    id: "wf_49", name: "End-of-Day Wrapup", category: "Reporting", icon: Clock, color: "#f59e0b",
    description: "Summarize today's activity, wins, tasks completed, and tomorrow's priorities.",
    projected_result: "End every day with clarity — never forget a follow-up",
    trigger: "Schedule", schedule: "Daily 6pm",
    linked_tools: ["executiveBrief", "groqSmartRouter", "sendSms"],
    steps: [
      { type: "trigger_schedule", label: "Daily 6pm" },
      { type: "executive_brief", label: "Daily Wrapup" },
      { type: "send_sms", label: "SMS Tomorrow's Top 3" },
      { type: "google_drive", label: "Save Daily Log" },
    ],
  },
  {
    id: "wf_50", name: "Full Autonomous Pipeline", category: "Operations", icon: Zap, color: "#d4af37",
    description: "The ultimate: scrape → score → research → email → follow-up → propose → close. Fully hands-off.",
    projected_result: "Autonomous revenue generation — $50K-$200K/quarter on autopilot",
    trigger: "Schedule", schedule: "Daily 6am",
    linked_tools: ["bulkLeadPipeline", "sendOutreachEmail", "generateProposal", "groqSmartRouter"],
    steps: [
      { type: "trigger_schedule", label: "Daily 6am" },
      { type: "bulk_pipeline", label: "Full Pipeline Run" },
      { type: "filter_leads", label: "Hot Leads (Score > 70)" },
      { type: "send_email", label: "Auto Outreach" },
      { type: "delay", label: "Wait 3 Days" },
      { type: "send_email", label: "Follow-Up" },
      { type: "filter_leads", label: "Responders" },
      { type: "generate_proposal", label: "Auto Proposal" },
      { type: "notify", label: "Pipeline Report" },
    ],
  },
];

export default WORKFLOW_TEMPLATES_50;